### ISSUE TITLE
[Running on MacOS] 测了下在macos上运行

### ISSUE THREAD

**Issue by Justsoos** [mzz2017/V2RayA#10]
由于mac docker desktop不支持host模式，也不能设置全局，就只作为端口代理，实测可用，ping测试也没问题：
下面三个命令：

```
docker volume create v2raya_shared-data
```

```
docker run -d \
    -p 2017:2017 \
    --restart=always \
    --privileged=true \
    -v v2raya_shared-data:/etc/v2ray \
    --name v2raya_backend \
    mzz2017/v2raya:stable
```

```
docker run -d \
    -p 20170-20172:20170-20172 \
    -p 12345:12345 \
    --restart=always \
    --privileged=true \
    --pid=container:v2raya_backend \
    -v v2raya_shared-data:/etc/v2ray \
    --env V2RAY_LOCATION_ASSET=/etc/v2ray \
    --name v2raya_v2ray \
    v2ray/official \
    /bin/sh -c "cp -rfu /usr/bin/v2ray/* /etc/v2ray/ && v2ray -config=/etc/v2ray/config.json"
```
貌似不需要pull golang:buster，当然了，没有 host 模式，http 测试是用不了的

**Comment by mzz2017** [comment]
全局代理依赖于iptables命令和TPPROXY模块，macos下无法使用是可以预见的，当然，感谢你的尝试。将会在之后的README中attach该issue。

**Comment by Justsoos** [comment]
哦，正好你在。
建议能web改 config.json，刚发现一个需要改 serverName的，目前找不到入口。
```
docker run --rm -it --privileged --pid=host walkerlee/nsenter -t 1 -m -u -i -n
```
nsneter 进去，发现 config.json 是只读的，而且改起来也不如 web 上方便
```
"tlsSettings": {
                    "allowInsecure": true,
                    "serverName": "Server_Name"
                }
```
v2ray 的配置复杂问题由来已久了，目前 v2raya 沿用的，还是 v2rayN 的作者定义的一个简化版 vmess URI，要做到通用 -- 改 config.json，应该受众用户更丰富

issue 到这里，也是为未来可能 Google 过来的人作个参考。

**Comment by Justsoos** [comment]
另外，如果 http 测试可限制在某个 高 port 范围，比如50500 - 50700，也可是试试用端口映射到本机，这样 mac 上没有 host 模式，也能用 http 测试了。就是不知道这样几百个端口同时占用，docker 会不会出现什么bug

**Comment by mzz2017** [comment]
config.json不应是只读的，你可以尝试在v2ray-core容器中修改它。

已了解需求，我目前在准备支持SSR协议（因为很多v2ray节点挂了，而SSR的受众不少），因此该feature的支持可能会向后推迟一段时间。

http测试是docker模式下的一个bug，下个版本将会修复，谢谢。

**Comment by Justsoos** [comment]
ha，我得到的情况正好相反，最近 ssr/ss 的挂的比例极高，v2 的某些协议稳定的多。

**Comment by mzz2017** [comment]
你好，经过测试以下述docker命令运行可以支持http测试，你可以更新issue，随后我会删除该条comment

```bash
docker volume create v2raya_shared-data

docker run -d \
    -p 2017:2017 \
    -p 20170-20172:20170-20172 \
    -p 12345:12345 \
    --restart=always \
    --privileged \
    -v v2raya_shared-data:/etc/v2ray \
    --name v2raya_backend \
    mzz2017/v2raya:stable

docker run -d \
    --restart=always \
    --privileged \
    --pid=container:v2raya_backend \
    --network=container:v2raya_backend \
    -v v2raya_shared-data:/etc/v2ray \
    --env V2RAY_LOCATION_ASSET=/etc/v2ray \
    --name v2raya_v2ray \
    v2ray/official \
    /bin/sh -c "cp -rfu /usr/bin/v2ray/* /etc/v2ray/ && v2ray -config=/etc/v2ray/config.json"
```

**Comment by Justsoos** [comment]
哦，好，命令已复制，我待会儿试试。
我来是提个建议：
最好在 sub，server 两种标签上加个比如棕黄色的点，标志这个sub下面某个server节点正在被激活。
我测设置了7个订阅，一时找不到那个节点被激活了，哈

**Comment by mzz2017** [comment]
了解，下个版本会添加

**Comment by Justsoos** [comment]
1，mac 上 http 测，用你上面命令有问题。
后来反复测，还以为容器上要开测试端口，看来不用。原来你少了个控制端口12345的配置命令，如下就可以了：
```
docker run -d \
    -p 2017:2017 \
    -p 20170-20172:20170-20172 \
    -p 12345:12345 \
    --restart=always \
    --privileged \
    -v v2raya_shared-data:/etc/v2ray \
    --name v2raya_backend \
    mzz2017/v2raya:stable

docker run -d \
    --restart=always \
    --privileged \
    --pid=container:v2raya_backend \
    --network=container:v2raya_backend \
    -v v2raya_shared-data:/etc/v2ray \
    --env V2RAY_LOCATION_ASSET=/etc/v2ray \
    --name v2raya_v2ray \
    v2ray/official \
    /bin/sh -c "cp -rfu /usr/bin/v2ray/* /etc/v2ray/ && v2ray -config=/etc/v2ray/config.json"
```

2，同时测试节点比较多 >20，或其他原因？
会出现提示
![image](https://user-images.githubusercontent.com/3480043/71326158-fc048000-2531-11ea-8931-9d71d08ad848.png)

之后在很长一段时间内进行 http测试，都会出现类似错误
```
Head https://google.com: socks connect tcp localhost:54322->google.com:443: dial tcp 127.0.0.1:54322: connect: connection refused
```
用 `docker restart v2raya_backend && docker restart v2raya_v2ray` 可以修正，只重启 v2raya_v2ray，还是可能出现同样错误。而且这个重启顺序应该不能变，变了也会出错

另外，如果使用正在连接的节点进行测试，也可能会出现上面的错误。

3，新发现了个bug，连接节点后，点击断开，并不会真正“断开”，还在继续运行。同时 “v2ray-core状态” 此时也是显示错误的 “尚未运行”

4，最好在 v2raya_shared-data 能有debug日志什么的 -- 我还没去看过有没有

**Comment by Justsoos** [comment]
docker 上那个主容器开端口貌似有说道，--pid 指向的 “主” 容器内，我用 nc 命令开端口数字，就是本地端口，但 “从” 容器 nc 开的端口是被随机掉的。 而且主容器运行的 nc 不能去连从开的本地端口，从可以连主开的端口

**Comment by Justsoos** [comment]
另外个建议，ping 和 http + sub 能变成浮动memu，方便在下翻到几十个节点上作测试时候，不用再上翻到最顶部找 menu 了

**Comment by Justsoos** [comment]
又测了下，可能是 golang 的资源回收机制，测太多节点，把端口资源耗尽了？
测80个节点的 http，`# ss -nat|wc` 测得同时在容器内开出的端口和连接超过440，过1分钟还没有释放的端口也有30+ 都是5万多的高端口，也可能是你预留的端口少限制了资源？

**Comment by Justsoos** [comment]
修改 config.json 的事儿就先放下了，你还是先搞 ssr 吧，我发现你全程都用的 v2rayN 对 vmess 的定义，包括在 `/etc/v2ray/v2raya.json` 里保存的，都是这样的格式， ... 这个。。。就没法改了啊，需要动大手术了 😓

**Comment by Justsoos** [comment]
确定了2个bug诱发方式，第一个是，混合多个ss和v2ray节点批量测 http 会导致
```
Head https://google.com: socks connect tcp localhost:54355->google.com:443: dial tcp 127.0.0.1:54355: connect: connection refused
```
错误，节点过多混合测试，还造成了几次容器完全不能用，必须删除容器重建 😰  

第二个方式，将已经连接的节点，也设置在测试内，也会引发这个错误，但多数不会引发容器失效

**Comment by Justsoos** [comment]
以上测试用的都是这个版本
```
"RepoDigests": [
            "mzz2017/v2raya@sha256:2f178eb435eb3e40bb22e6a8a5aa03caaa39a0c5e8aabf7e36a8111b7b938f8f"
        ]
```

**Comment by Justsoos** [comment]
更新下测试情况，只要有一个已经连接上的节点，再 http 测其他节点，都可能出现上面的错误，而且经常处于不可逆错误，必须删掉容器重建才能再次 http 测试，`docker ps -a`可见 v2ray/official 容器一直在被反复重启：
```
Restarting (137) 26 seconds ago
```。

**Comment by mzz2017** [comment]
修复进度：
- [x] 节点激活标记
- [x] 测试http时延出现connection refused
- [x] 浮动toolbar
- [ ] 未复现`新发现了个bug，连接节点后，点击断开，并不会真正“断开”，还在继续运行。同时 “v2ray-core状态” 此时也是显示错误的 “尚未运行”`
- [ ] 未复现`同时测试节点比较多 >20，或其他原因会出现提示Docker模式下频繁更换配置`
- [ ] TODO `测试http时延时开放端口过多`
- [ ] TODO `错误日志`

有意帮助复现可加telegram @mzz2017

**Comment by Justsoos** [comment]
目前用来在 macos 上，只作本地端口代理 -- 即 ssr-ss-v2ray 全能客户端，**不涉及透明代理**（win 和 linux 应该都是可用的）使用的 “一键脚本” 如下：

1，如果第一次用，创建 数据盘，这个命令只需要 **运行一次**，除非你想删除所有旧数据：
```docker volume create v2raya_shared-data```

2，运行如下脚本：
```
docker rm -f v2raya_backend v2raya_v2ray v2raya-gui \
&& \
docker run -d \
    -p 2017:2017 \
    -p 20170-20172:20170-20172 \
    -p 12345:12345 \
    --restart=always \
    --privileged \
    -v v2raya_shared-data:/etc/v2ray \
    --name v2raya_backend \
    mzz2017/v2raya:stable \
&& \
docker run -d \
    --restart=always \
    --privileged \
    --pid=container:v2raya_backend \
    --network=container:v2raya_backend \
    -v v2raya_shared-data:/etc/v2ray \
    --env V2RAY_LOCATION_ASSET=/etc/v2ray \
    --name v2raya_v2ray \
    v2ray/official \
    /bin/sh -c "cp -rfu /usr/bin/v2ray/* /etc/v2ray/ && v2ray -config=/etc/v2ray/config.json" \
&& \
docker run --name v2raya-gui -d -p 8080:80 mzz2017/v2raya-gui
```
最新版本的 docker desktop 都会自行 pull 镜像，不需要人工干预。

3，打开浏览器，访问`http://127.0.0.1:8080`，设置用户名密码，就可以用了

4，另外，需要升级 镜像 的，用此命令停止并删除运行中的容器，然后重复上面 2 步骤即可：
```docker rm -f v2raya_backend v2raya_v2ray v2raya-gui```
