### ISSUE TITLE
[BUG] 未发现GFWList文件，请更新GFWList后再试

### ISSUE THREAD

**Issue by ichenkaihua** [mzz2017/V2RayA#11]
**描述问题**
设置里选GFWList保存时提示"未发现GFWList文件，请更新GFWList后再试"
版本:0.5.7
系统:manjaro-arm pi4

**复现问题的步骤**
菜单-》设置-》全局透明代理-》GFWList-》保存设置

**预期结果**
自动下载gfwlist

**截图**

**Comment by mzz2017** [comment]
设置的最上方有个更新，点一下就下载了------------------ 原始邮件 ------------------
发件人: "chenkaihua"<notifications@github.com>
发送时间: 2020年1月1日(星期三) 下午5:17
收件人: "mzz2017/V2RayA"<V2RayA@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [mzz2017/V2RayA] [BUG] 未发现GFWList文件，请更新GFWList后再试 (#11)



描述问题
 设置里选GFWList保存时提示"未发现GFWList文&#x4EF6;，请更新GFWList后再试"
 版本:0.5.7
 系统:manjaro-arm pi4
 
复现问题的步骤
 菜单-》设置-》全局透明代理-》GFWList-》保存设置
 
预期结果
 自动下载gfwlist
 
截图
 
&mdash;

**Comment by ichenkaihua** [comment]
没注意看，打扰了，可以关闭了
