### ISSUE TITLE
ssr无法连接网络

### ISSUE THREAD

**Issue by powerButweak** [mzz2017/V2RayA#15]
如何使用ssr配置文件？

系统: pop!_os 19.10 基于ubuntu 19.10

使用v2ray配置文件 系统端口设置为20171, 20170 能正常使用
但端口20171, 20170无法使用ssr ，其他端口中的12346 是否需要设置, 系统设置socks 端口 12346无效，还是无法连接

**Comment by mzz2017** [comment]
ssr无需特殊配置，请确定：
1. SSR节点在其他工具中确实可以正常使用
2. 如果可以正常使用，请提供加密方式、混淆方式、协议、以及协议参数和混淆参数，以助调试

**Comment by powerButweak** [comment]
1. 同一个节点，手机端的ssr可以，windows的ssr也可以，linux 上 electron ssr 也能连接
    
2. 
    加密方式 chacha20
    Protocol  auth_aes128_sha1
    Obfs plain

**Comment by mzz2017** [comment]
![image](https://user-images.githubusercontent.com/30586220/72355388-530d0780-3722-11ea-93fb-f413caadd258.png)

我这边复现不是很成功，在上述配置下可以正常使用，如果可以分享节点的话可以加telegram：https://t.me/joinchat/Lci6NVWB-x0Htm_woS6frA

**Comment by rc2md3** [comment]
ssr使用过程中出现间接性断开连接，在其他软件上节点正常

**Comment by mzz2017** [comment]
> ssr使用过程中出现间接性断开连接，在其他软件上节点正常，感觉可能是socks5转发问题

@rc2md3 具体表现在什么使用场景（下载、浏览网页），参数是什么，请另开issue，有条件请附图，谢谢

**Comment by mzz2017** [comment]
已修复，可通过docker方式拉取latest镜像尝鲜，测试稳定后会将其推上apt、aur、stable等。

**Comment by mzz2017** [comment]
将V2RayA更新至最新版即可。
