### ISSUE TITLE
Chrome该网页无法正常运作

### ISSUE THREAD

**Issue by willon295** [mzz2017/V2RayA#16]
**描述问题**
系统： Arch
1. 能连接成功
2. 终端 可以 Ping 通 Google
3. Chrome无法正常访问Google网页（该网页无法正常运作）

**Comment by mzz2017** [comment]
可以ping通谷歌这件事可以一定程度上反映出dns被污染了。
为了进一步验证，关闭全局代理，键入一行命令
```bash
http_proxy=localhost:20171 https_proxy=localhost:20171 curl -v google.com
```

**Comment by mzz2017** [comment]
@willon295 最新版本可设置规避DNS污染
