### ISSUE TITLE
群晖使用docker无法透明代理

### ISSUE THREAD

**Issue by lsl330** [mzz2017/V2RayA#17]
设置透明代理，保存显示iptables-legacy -t mangle -A SSTP_PRE -m mark --mark 1 -p tcp -j TPROXY --on-port 12345 --tproxy-mark 1 exit status 2 iptables v1.8.3 (legacy): unknown option "--on-port" Try `iptables -h' or 'iptables --help' for more information.

**Comment by mzz2017** [comment]
群晖执行`lsmod|grep xt_TPROXY`以查看tproxy支持情况

**Comment by mzz2017** [comment]
无回馈，关闭问题
