### ISSUE TITLE
这个是否可以部署在NAS上?

### ISSUE THREAD

**Issue by weiyideai520** [mzz2017/V2RayA#2]
这个是否可以通过 docker 部署在NAS上，然后其他设备通过走代理模式，实现全局透明代理呢？
----------
现在有一个官方的V2ary可以通过Docker部署在NAS，但是确实缺点就是没办法实现透明代理。

**Comment by weiyideai520** [comment]
我手里有一台华芸的NAS，就docker安装最方便咯，其他的安装不大会。我昨天尝试了在NAS用Docker安装这个软件。能安装上，但是建议添加一个功能，就是能修改 “https://v2raya.mzz.pub/” 默认设置的地址，现在指定的设置地址是 localhost，我希望能修改成我NAS的ip地址。

**Comment by mzz2017** [comment]
配置服务端地址正在日程。
docker安装的不支持透明代理。
目前正在实现apt-get安装，同时也会打包成rpm，你那台NAS是什么系统，支持apt吗

**Comment by weiyideai520** [comment]
我也不太清楚我的NAS是啥系统，我今天修改了 webui里面的地址，部署好了
![Snipaste_2019-11-20_17-59-02](https://user-images.githubusercontent.com/2784569/69228977-88ccbe80-0bbf-11ea-88b4-32e3b0ef869c.png)
![Snipaste_2019-11-20_17-58-53](https://user-images.githubusercontent.com/2784569/69228983-8a968200-0bbf-11ea-8ca6-835074c2b257.png)
-------
至少服务端看起来是没有什么问题了。我在手机选择 http代理，设置好地址和端口，发现并不能上网，不知道问题出在了哪里。
![Snipaste_2019-11-20_18-01-13](https://user-images.githubusercontent.com/2784569/69229099-c2052e80-0bbf-11ea-81c8-511933cf41c0.png)

**Comment by mzz2017** [comment]
你好，你是使用docker-compose部署的吗？如果不是使用docker-compose而是直接使用docker命令，需要将v2ray也运行于docker并遵循配置。
方便的话可以将微信发至我的邮箱m@mzz.pub，以方便详细交流。

**Comment by mzz2017** [comment]
题主通过portainer.io UI界面配置docker，已参考[docker-compose.yml](https://github.com/mzz2017/V2RayA/blob/master/docker-compose.yml)完成配置解决问题。

**Comment by mzz2017** [comment]
@weiyideai520 最新版本已可自定义地址、端口，以及在docker模式下支持全局透明代理（待充分测试）
