### ISSUE TITLE
[BUG] v2ray/official is always restarting, docker部属无法启动

### ISSUE THREAD

**Issue by cnscorpions** [mzz2017/V2RayA#20]
**描述问题**
简要描述问题
使用 docker 命令部署，无法启动应用，终端中显示v2ray/official 容器一直在restart

环境参数：
OS: Ubuntu 18.04.3 LTS x86_64
Kernel: 4.15.0-20-generic 
Docker version 19.03.5, build 633a0ea838

**复现问题的步骤**
如何复现问题
1. `docker pull mzz2017/v2raya:stable`
2. `docker pull v2ray/official`
3. `docker volume create v2raya_shared-data`
4. `docker run -d \
	--restart=always \
	--privileged \
	--network=host \
	-v v2raya_shared-data:/etc/v2ray \
	-v /etc/localtime:/etc/localtime:ro \
	-v /etc/timezone:/etc/timezone:ro \
	--name v2raya_backend \
	mzz2017/v2raya:stable`
5. `docker run -d \
	--restart=always \
	--privileged \
	--network=host \
	--pid=container:v2raya_backend \
	-v v2raya_shared-data:/etc/v2ray \
	--env V2RAY_LOCATION_ASSET=/etc/v2ray \
	--name v2raya_v2ray \
	v2ray/official \
	sh -c "cp -rfu /usr/bin/v2ray/* /etc/v2ray/ && v2ray -config=/etc/v2ray/config.json"`

**预期结果**
简要讲述执行正确时预期的结果
此时打开demo链接，能够顺利使用

**日志**
`V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to load config: /etc/v2ray/config.json > v2ray.com/core/main/confloader/external: config file not readable > open /etc/v2ray/config.json: no such file or directory`

**截图**
如果条件允许请附图

**Comment by mzz2017** [comment]
执行`docker images v2ray/official`以获取IMAGE ID

**Comment by cnscorpions** [comment]
不好意思，换成从从软件源安装，已经正常使用了
