### ISSUE TITLE
使用docker-compose up 的方式启动，报错

### ISSUE THREAD

**Issue by xfdywy** [mzz2017/V2RayA#22]
## 预期的行为和实际行为

使用docker-compose up 的方式启动，报错， log如下

Starting v2raya_backend_1 ... done
Starting v2raya_v2ray_1   ... done
Attaching to v2raya_backend_1, v2raya_v2ray_1
backend_1  | V2RayLocationAsset is /etc/v2ray
backend_1  | V2Ray binary is at /etc/v2ray/v2ray
backend_1  | V2RayA is running in Docker. Compatible mode starts up.
backend_1  | Waiting for official/v2ray's running. Refer: https://github.com/mzz2017/V2RayA#docker%E6%96%B9%E5%BC%8F
v2ray_1    | V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
v2ray_1    | A unified platform for anti-censorship.
v2ray_1    | main: failed to load config: /etc/v2ray/config.json > v2ray.com/core/main/confloader/external: config file not readable > open /etc/v2ray/config.json: no such file or directory
backend_1  | 2020/02/02 21:20:28 asset.go:129: open /etc/v2ray/config.json: no such file or directory
v2raya_v2ray_1 exited with code 23
v2raya_v2ray_1 exited with code 23

> 如果是feature建议，请写在这里

## 重现问题的步骤

> 如果条件允许请附图。如果是feature建议，请省略。

**Comment by xfdywy** [comment]
![image](https://user-images.githubusercontent.com/6959554/73608993-39b1f980-4604-11ea-853b-c3d8f7cc3b26.png)

**Comment by mzz2017** [comment]
可先通过软件源安装，稍后紧急修复，谢谢

**Comment by mzz2017** [comment]
已修复
