### ISSUE TITLE
问一个关于订阅的小白问题

### ISSUE THREAD

**Issue by xfdywy** [mzz2017/V2RayA#23]
## 预期的行为和实际行为

我在别的网站购买了v2ray的服务器，并且提供了订阅地址。这个地址可以直接填到v2ray的windows和手机客户端上，之后更新订阅就可以获取服务器地址。 v2raya 看起来也可以导入订阅，为什么我只能导入一个一个的服务器呢？ 我需要在导入的时候填写什么？ 目前我点导入后，填写的是类似于这样的订阅地址：https://xxxxx.xxx.xx 。 会提示
![image](https://user-images.githubusercontent.com/6959554/73611431-c10b6700-461c-11ea-9089-a3ab99efcbef.png)

我确认这个订阅地址有效

> 如果是feature建议，请写在这里

## 重现问题的步骤

> 如果条件允许请附图。如果是feature建议，请省略。

**Comment by mzz2017** [comment]
V2RayA支持订阅，按照下列步骤排查问题：
1. 浏览器打开https://xxxxx.xxx.xx是否可以打开
2. 执行`curl -v https://xxxxx.xxx.xx`，查看结果
3. 在V2RayA已连接节点时，执行`https_proxy=localhost:20171 curl -v https://xxxxx.xxx.xx`，查看结果`
4. 请截图V2RayA的设置

**Comment by xfdywy** [comment]
我昨天是自己编译运行的， 不可以，今天换成源安装，可以了。谢谢～
