### ISSUE TITLE
[BUG] 部分代理连接后不能访问目标地址

### ISSUE THREAD

**Issue by 0x012FA733** [mzz2017/V2RayA#25]
**描述问题**
使用 v0.6.3.1+ 版本以后部分代理连接后无法访问网站, firefox 提示见截图1

**复现问题的步骤**
使用 v0.6.3- 同一代理连接后可以正常访问, 怀疑与部分代理访问时不支持使用目标 IP 连接有关? 见截图2

**预期结果**
增加网址 / IP切换开关?

**截图**
![1](https://user-images.githubusercontent.com/49284128/73755192-a235dd80-47a0-11ea-80eb-d60df5b7a0c5.png)
![2](https://user-images.githubusercontent.com/49284128/73755226-acf07280-47a0-11ea-8146-2d7440d62d8a.png)

**Comment by mzz2017** [comment]
了解，考虑到切换的复杂性，下个版本将取消域名解析

**Comment by mzz2017** [comment]
@0x012FA733  由于缺少复现条件，可否尝试删除这段代码来测试问题是否解决？

**Comment by mzz2017** [comment]
或者手动修改v2ray的config.json，将ip改回url后重启v2ray服务

**Comment by 0x012FA733** [comment]
> @0x012FA733 由于缺少复现条件，可否尝试删除这段代码来测试问题是否解决？

v0.6.5 注释这段代码后测试, 问题解决, 期待下个版本, 谢谢

**Comment by fuck2ky** [comment]
应该是cdn导致的

**Comment by mzz2017** [comment]
v0.6.5.1已紧急修复
