### ISSUE TITLE
v2ray-core 4.22.0与4.22.1版本DoH查询较慢

### ISSUE THREAD

**Issue by mzz2017** [mzz2017/v2rayA#26]
如果您使用V2RayA开启DoH(DNS over HTTPS)发现dns查询速度极慢，且增大了QoS的几率，请暂时不要使用DoH。

目前的v2ray-core(4.22.0 - 4.22.1)确实存在这样的问题，详见PR[#2212](https://github.com/v2ray/v2ray-core/pull/2212)。

在PR被合并后，V2RayA会跟进一些提示性更新。

**Comment by cnscorpions** [comment]
关掉DOH，会好很多

**Comment by mzz2017** [comment]
v2ray-core最新版已发布，已修复相关问题。
