### ISSUE TITLE
[BUG] 在 Debian 10.2 下，无法启动

### ISSUE THREAD

**Issue by atzlinux** [mzz2017/V2RayA#27]
执行就报错退出哈：

v2raya 
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
V2RayA/model/v2ray.GetV2rayServiceFilePath(0xc000040600, 0xc000543e38, 0x4e1321, 0xf35da0)
	/home/travis/gopath/src/github.com/mzz2017/V2RayA/service/model/v2ray/v2rayService.go:70 +0x329
V2RayA/model/v2ray.LiberalizeProcFile(0xc0000b0000, 0x13)
	/home/travis/gopath/src/github.com/mzz2017/V2RayA/service/model/v2ray/v2rayService.go:78 +0x4a
main.initConfigure()
	/home/travis/gopath/src/github.com/mzz2017/V2RayA/service/main.go:63 +0x68
main.main()
	/home/travis/gopath/src/github.com/mzz2017/V2RayA/service/main.go:236 +0x9a

**Comment by mzz2017** [comment]
你好，请根据README先行安装v2ray-core，我已在debian10.2测试通过。

**Comment by mzz2017** [comment]
v0.6.5.1已更新错误提示
