### ISSUE TITLE
[BUG] installer_debian_v0.6.5.deb ,这个包，卸载的时候报错，导致无法卸载

### ISSUE THREAD

**Issue by atzlinux** [mzz2017/V2RayA#28]
**描述问题**

 installer_debian_v0.6.5.deb ,这个包，卸载的时候报错，导致无法卸载

卸载脚本，和 debian 不兼容。需要修改下。

**Comment by mzz2017** [comment]
你好，具体报错是什么呢

**Comment by mzz2017** [comment]
我这里看到是v2ray.service not loaded，说明v2ray未安装，已悉知，下个版本修复

**Comment by atzlinux** [comment]
如果没有安装 v2ray-core 的服务，你这个软件包启动，卸载都会报错。

你知道哪里有打包好的 v2ray-core 的 deb 包吗？

**Comment by mzz2017** [comment]
目前采用的是分离式的做法。
您可自行将安装脚本打包为deb包，可见https://github.com/jordansissel/fpm。

**Comment by mzz2017** [comment]
v0.6.5.1已修复
