### ISSUE TITLE
[Feature] 希望加入修改密码的功能

### ISSUE THREAD

**Issue by codexvn** [mzz2017/V2RayA#32]
**Feature内容**
目前版本并不支持修改密码，是否以后会加入这个功能？

**Comment by mzz2017** [comment]
目前可以通过删除/etc/v2ray/v2raya.json中的accounts来重新创建账号，将来考虑以command的方式创建、列出、修改账户。

**Comment by mzz2017** [comment]
![image](https://user-images.githubusercontent.com/30586220/75543531-f01aca00-5a5c-11ea-852e-6f7f9aea682f.png)

 `0.6.7.2`新增参数`--reset-password`

**Comment by zz5678** [comment]
目前新版已经没有 /etc/v2ray/v2raya.json 了，只有一个 0.dat 文件，升级系统情况下，备份/恢复这个数据文件就可以了吗？

**Comment by mzz2017** [comment]
> 目前新版已经没有 /etc/v2ray/v2raya.json 了，只有一个 0.dat 文件，升级系统情况下，备份/恢复这个数据文件就可以了吗？

是的

**Comment by AIxWALL** [comment]
docker 怎么修改密码

**Comment by AIxWALL** [comment]
docker 怎么修改密码

**Comment by mzz2017** [comment]
@AIxWALL 先把容器停下： docker stop 容器名，然后运行另一个容器，修改密码： docker run -it --volumes-from 刚停的容器名 mzz2017/v2raya --reset-password

**Comment by popofthedead** [comment]
windows如何修改密码?

**Comment by MarksonHon** [comment]
> windows如何修改密码?

如果你是scoop安装的，那么直接
`v2raya --lite --reset-password`
如果你是安装包安装的，那就先停止v2rayA这个服务，然后进入安装路径，打开一个具有管理员权限的PowerShell或cmd窗口，然后运行：
`v2raya --lite --reset-password --config ./`

**Comment by popofthedead** [comment]
我是安装包安装的，实测无法直接用v2raya命令，必须用v2raya_windows_x64_*.exe

**Comment by 1798972** [comment]
## Docker下重置密码

1.停止旧的容器A

```bash
docker stop xx
```

2.利用新容器B重置密码

```bash
docker run -it --volumes-from 刚停的容器名 mzz2017/v2raya --reset-password
```

3.重启旧容器A

> 此时容器A的密码已经被重置，重新打开后管页面时提示创建账户，但旧数据会保留。

```bash
docker start xx
```

4.可以删除临时容器B

```bash
docker rm clever_hermann
```
