### ISSUE TITLE
GFWList 更新总是失败

### ISSUE THREAD

**Issue by yichangshengwu** [mzz2017/V2RayA#33]
环境：arch linux
软件：通过 release 中的 installer 安装，版本为最新，

问题：gfwlist 更新总是失败，详见下图，

![截图_2020-02-07_21-06-46](https://user-images.githubusercontent.com/43059917/74032417-dc94ba00-49ee-11ea-8179-f7fa457894a6.png)

不知道如果更新成功的话，文件会保留在哪里，
不然可以下载下来手动替换，（文件已经下载下来）

**Comment by mzz2017** [comment]
启动时会有提示，如
```bash
[mzz@mzz-pc ~]$ systemctl status v2raya
● v2raya.service - V2RayA Service
   Loaded: loaded (/usr/lib/systemd/system/v2raya.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-02-07 21:09:10 HKT; 22min ago
     Docs: https://github.com/mzz2017/V2RayA/blob/master/README.md
 Main PID: 603 (v2raya)
    Tasks: 16 (limit: 4915)
   Memory: 106.7M
   CGroup: /system.slice/v2raya.service
           └─603 /usr/bin/v2raya

2月 07 21:09:10 mzz-pc systemd[1]: Started V2RayA Service.
2月 07 21:09:11 mzz-pc v2raya[603]: V2RayLocationAsset is /usr/lib/v2ray
2月 07 21:09:11 mzz-pc v2raya[603]: V2Ray binary is at /usr/lib/v2ray/v2ray
2月 07 21:09:11 mzz-pc v2raya[603]: V2RayA working directory is /
2月 07 21:09:11 mzz-pc v2raya[603]: Version: 0.6.5.1
2月 07 21:09:11 mzz-pc v2raya[603]: V2RayA is running at 0.0.0.0:2017
2月 07 21:09:13 mzz-pc v2raya[603]: GUI demo: https://v2raya.mzz.pub
```
其中`V2RayLocationAsset`存放dat文件

**Comment by yichangshengwu** [comment]
> 启动时会有提示，如
> 
> ```shell
> [mzz@mzz-pc ~]$ systemctl status v2raya
> ● v2raya.service - V2RayA Service
>    Loaded: loaded (/usr/lib/systemd/system/v2raya.service; enabled; vendor preset: disabled)
>    Active: active (running) since Fri 2020-02-07 21:09:10 HKT; 22min ago
>      Docs: https://github.com/mzz2017/V2RayA/blob/master/README.md
>  Main PID: 603 (v2raya)
>     Tasks: 16 (limit: 4915)
>    Memory: 106.7M
>    CGroup: /system.slice/v2raya.service
>            └─603 /usr/bin/v2raya
> 
> 2月 07 21:09:10 mzz-pc systemd[1]: Started V2RayA Service.
> 2月 07 21:09:11 mzz-pc v2raya[603]: V2RayLocationAsset is /usr/lib/v2ray
> 2月 07 21:09:11 mzz-pc v2raya[603]: V2Ray binary is at /usr/lib/v2ray/v2ray
> 2月 07 21:09:11 mzz-pc v2raya[603]: V2RayA working directory is /
> 2月 07 21:09:11 mzz-pc v2raya[603]: Version: 0.6.5.1
> 2月 07 21:09:11 mzz-pc v2raya[603]: V2RayA is running at 0.0.0.0:2017
> 2月 07 21:09:13 mzz-pc v2raya[603]: GUI demo: https://v2raya.mzz.pub
> ```
> 
> 其中`V2RayLocationAsset`存放dat文件

想问是否需要修改文件名，
结果复制进去后一刷新就已经认到了，

感谢您的解答。
