### ISSUE TITLE
[BUG] 已是 Root 环境，依旧提示没有权限

### ISSUE THREAD

**Issue by Flyfish233** [mzz2017/V2RayA#34]
**描述问题**

`root@localhost:/# ./home/pi/v2ray`
`2020/02/10 18:36:20 请以sudo或root权限执行本程序`

**复现问题的步骤**

始终如此，权限 7777，任何方法都无法启动
设备系统经修改，官方 Raspbian 可用。使用 ARM 编译版本。
`Linux version 4.19.79-OPENFANS+20191013-v8 (root@raspbian) (gcc version 9.1.0 (GCC)) #1 SMP PREEMPT Sun Oct 13 16:06:07 CST 2019`

**可能方案**

不知道是怎么检查 Root 的，如果可能，您能否加一个跳过 Root 检查的选项？

**Comment by Flyfish233** [comment]
`root@localhost:/# id root`
`uid=0(root) gid=0(root) groups=0(root)`
`root@localhost:/# ./home/pi/v2ray`
`2020/02/10 18:50:24 请以sudo或root权限执行本程序`

**Comment by mzz2017** [comment]
可暂时删去main.go中
```go
	if os.Getegid() != 0 {
		log.Fatal("请以sudo或root权限执行本程序")
	}
```
随后交叉编译
```bash
GOOS=linux GOARCH=arm go build .
```

**Comment by mzz2017** [comment]
version: v0.6.5.3
可通过`--passcheckroot`跳过
```bash
$ v2raya --help
Usage of v2raya:
  -a, --address string      监听地址 (default "0.0.0.0:2017")
  -c, --config string       V2RayA配置文件路径 (default "/etc/v2ray/v2raya.json")
  -m, --mode string         可选systemctl, service, docker, common. 不设置则自动检测
  -s, --ssrlistenport int   使用ss或ssr时的ssr server监听端口，默认12346 (default 12346)
      --passcheckroot       可跳过启动时的权限检查
  -h, --help                print this help menu

```
