### ISSUE TITLE
[Feature] 希望将脚本地址以及脚本内的下载地址放置到国内服务器

### ISSUE THREAD

**Issue by thtomatic** [mzz2017/V2RayA#36]
没外网的时候有时github连不上 根本部署不了
用这个 天翼云盘支持直链
https://github.com/xytoki/TCShare

**Comment by mzz2017** [comment]
很棒的提议，欢迎PR

目前有两个需要放到cdn做加速：
1. v2ray的安装脚本
2. 安装脚本内的v2ray的release

目前1是长期不变的，很容易做。

难点在于2，如`https://github.com/v2ray/v2ray-core/releases/download/${NEW_VER}/v2ray-linux-${VDIS}.zip`

去年有个项目<https://github.com/v2ray/dist/>将release放到了代码中，大概是通过travis自动部署，以此来使用jsdelivr提供的cdn，如`https://cdn.jsdelivr.net/gh/v2ray/dist/v2ray-linux-${VDIS}.zip`

我认为效果是很不错的，但不知道为什么断更了。

在项目前段时间我使用ustc的github镜像以达到加速效果，而今天发现该镜像已经将大部分请求都302掉了。

所以说这样一个问题目前还是没有找到一个愉快的解决方案。

**Comment by thtomatic** [comment]
安装脚本内的v2ray的release   个人觉的小版本更新没必要用最新的，大版本更新的时候可以手动更新下安装脚本内的下载地址
或者：
https://api.github.com/repos/v2ray/v2ray-core/releases/22545481/assets
用这个api获取最新版下载地址，再用个国外机子做中转下载，自动同步到天翼云盘（这个方案可能需要花钱。。。不过阿里云最近有活动 国际版香港免费一年）

**Comment by mzz2017** [comment]
已将安装脚本放到cdn.jsdelivr.net
