### ISSUE TITLE
[BUG] AUR PKGBUILD 添加桌面图标时错误

### ISSUE THREAD

**Issue by 0x012FA733** [mzz2017/V2RayA#37]
**描述问题**
当运行到 `package()` 时, 出现 `ERROR: ld.so: object 'libfakeroot.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.` 和 `sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper`

**复现问题的步骤**
出现问题的地方如截图, 但是*不用复现啦, 可修复*

**预期结果**
*顺利安装, 修复方式如下*
```
diff --git a/PKGBUILD b/PKGBUILD
index 853cc77..73778ff 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -27,7 +27,7 @@ package() {
     install -Dm755 "service/v2raya" -t "$pkgdir/usr/bin/"
     
     ICON_SOURCE=gui/public/img/icons
-    ICON_TARGET=/usr/share/icons
-    sudo install -Dm644 "$ICON_SOURCE/android-chrome-512x512.png" "$ICON_TARGET/v2raya.png"
-    sudo install -Dm755 "install/v2raya.desktop" -t "$pkgdir/usr/share/applications/"
+    ICON_TARGET=$pkgdir/usr/share/icons
+    install -Dm644 "$ICON_SOURCE/android-chrome-512x512.png" "$ICON_TARGET/v2raya.png"
+    install -Dm755 "install/v2raya.desktop" -t "$pkgdir/usr/share/applications/"
 }
```

**截图**
![Screenshot from 2020-02-11 16-07-27](https://user-images.githubusercontent.com/49284128/74220567-ed914400-4cea-11ea-8e50-ab307301f3b6.png)

**Comment by mzz2017** [comment]
fixed
