### ISSUE TITLE
[BUG] 在树莓派上安装出错

### ISSUE THREAD

**Issue by 857487** [mzz2017/V2RayA#39]
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-1017-raspi2 aarch64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Feb 14 15:51:22 UTC 2020

  System load:  0.13              Processes:           126
  Usage of /:   2.9% of 57.35GB   Users logged in:     1
  Memory usage: 28%               IP address for eth0: 192.168.8.102
  Swap usage:   0%

0 packages can be updated.
0 updates are security updates.

Your Hardware Enablement Stack (HWE) is supported until April 2023.

Last login: Fri Feb 14 15:34:28 2020 from 192.168.1.3
ubuntu@ubuntu:~$ sudo apt update
Hit:1 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic InRelease
Hit:2 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic-updates InRelease
Hit:3 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic-backports InRelease
Hit:4 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic-security InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
ubuntu@ubuntu:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ubuntu@ubuntu:~$ sudo apt dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ubuntu@ubuntu:~$ curl -L -s https://github.com/mzz2017/V2RayA/raw/master/install/go.sh | sudo -E bash -s - --source ustc
ubuntu@ubuntu:~$ ls
ubuntu@ubuntu:~$ wget -qO - https://apt.v2raya.mzz.pub/key/public-key.asc | sudo apt-key add -
OK
ubuntu@ubuntu:~$ sudo add-apt-repository 'deb https://apt.v2raya.mzz.pub/ v2raya main'
Hit:1 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic InRelease
Hit:2 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic-updates InRelease
Hit:3 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic-backports InRelease
Hit:4 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic-security InRelease
Get:5 https://apt.v2raya.mzz.pub v2raya InRelease
Fetched 1437 B in 4s (327 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://apt.v2raya.mzz.pub v2raya InRelease' doesn't support architecture 'arm64'
ubuntu@ubuntu:~$ sudo apt-get update
Get:1 https://apt.v2raya.mzz.pub v2raya InRelease
Hit:2 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic InRelease
Hit:3 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic-updates InRelease
Hit:4 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic-backports InRelease
Hit:5 http://chinanet.mirrors.ustc.edu.cn/ubuntu-ports bionic-security InRelease
Fetched 1437 B in 7s (199 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://apt.v2raya.mzz.pub v2raya InRelease' doesn't support architecture 'arm64'
ubuntu@ubuntu:~$ sudo apt-get install v2raya
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package v2raya

**Comment by mzz2017** [comment]
了解，明天更新

**Comment by 857487** [comment]
谢谢，幸苦了!

**Comment by mzz2017** [comment]
@857487 fixed
