### ISSUE TITLE
连接出现exit code: 127

### ISSUE THREAD

**Issue by RebornL** [mzz2017/V2RayA#4]
## 预期的行为和实际行为
按照readme进行安装完成后，然后订阅成功，选择节点连接出现失败，显示exit code:127。请问这个出错的原因是什么？

## 重现问题的步骤
点击连接就出现了

> 如果条件允许请附图。如果是feature建议，请省略。
![Screenshot from 2019-11-23 09-48-37](https://user-images.githubusercontent.com/13940893/69471082-8bedc780-0dd6-11ea-9291-c24a105751eb.png)

**Comment by mzz2017** [comment]
你好，感谢issue，请终端键入下述两行命令
sudo systemctl status v2ray
sudo cat /etc/v2ray/config.json
并提供反馈的结果😋

**Comment by RebornL** [comment]
> 你好，感谢issue，请终端键入下述两行命令
> sudo systemctl status v2ray
> sudo ls -lh /etc/v2ray/
> 并提供反馈的结果

你好这是截图截图显示
![Screenshot from 2019-11-23 10-23-42](https://user-images.githubusercontent.com/13940893/69471540-5e574d00-0ddb-11ea-8461-c3fa05454781.png)

**Comment by mzz2017** [comment]
请提供

sudo cat /etc/v2ray/config.json

的结果，注意将id、aid关键信息打码

**Comment by RebornL** [comment]
> 请提供
> 
> sudo cat /etc/v2ray/config.json
> 
> 的结果，注意将id、aid关键信息打码

{"log":{"access":"/dev/null","error":"/dev/null","loglevel":"/dev/null"},"inbounds":[{"port":20170,"protocol":"socks","listen":"0.0.0.0","sniffing":{"enabled":true,"destOverride":["http","tls"]},"settings":{"auth":"noauth","udp":true},"streamSettings":null,"tag":"socks"},{"port":20171,"protocol":"http","listen":"0.0.0.0","sniffing":{"enabled":true,"destOverride":["http","tls"]},"settings":{"auth":"noauth","udp":true},"streamSettings":null,"tag":"http"},{"port":20172,"protocol":"http","listen":"0.0.0.0","sniffing":{"enabled":true,"destOverride":["http","tls"]},"settings":{"auth":"noauth","udp":true},"streamSettings":null,"tag":"pac"}],"outbounds":[{"tag":"proxy","protocol":"vmess","settings":{"vnext":[{"address":"157.254.26.192","port":1111,"users":[{"id":"XXX","alterId":0,"security":"auto"}]}],"servers":null},"streamSettings":{"network":"ws","wsSettings":{"connectionReuse":true,"path":"","headers":{"Host":"singtel.caipin.pro"}}},"mux":{"enabled":false,"concurrency":8}},{"tag":"direct","protocol":"freedom","settings":{"vnext":null,"servers":null}}],"routing":{"domainStrategy":"IPOnDemand","rules":[{"type":"field","outboundTag":"direct","inboundTag":["pac"],"domain":["geosite:cn"]},{"type":"field","outboundTag":"direct","inboundTag":["pac"],"ip":["geoip:cn","geoip:private"]}]}}

**Comment by mzz2017** [comment]
收到，我现在手边没有电脑，回去之后再仔细看看

**Comment by RebornL** [comment]
> 收到，我现在手边没有电脑，回去之后再仔细看看

麻烦了^^

**Comment by mzz2017** [comment]
你好，我这里可以运行这个配置，请查看20170-20172端口是否被其他程序占用

`sudo netstat -tlp | grep 2017`

**Comment by RebornL** [comment]
> 你好，我这里可以运行这个配置，请查看20170-20172端口是否被其他程序占用
> 
> `sudo netstat -nlp | grep 2017`

好的，我下午回去试试，如果是端口占用，我要怎么改动，是要改动config.json文件，还是在v2raya中设置进行修改？

**Comment by mzz2017** [comment]
查看是什么程序占用了端口，能否解决冲突，如果不行的话暂时只能通过修改v2raya服务端源代码解决，其后我会实现修改端口的功能。------------------ 原始邮件 ------------------
发件人: "RebornL"<notifications@github.com>
发送时间: 2019年11月23日(星期六) 中午1:20
收件人: "mzz2017/V2RayA"<V2RayA@noreply.github.com>;
抄送: "mzz"<m@mzz.pub>;"Comment"<comment@noreply.github.com>;
主题: Re: [mzz2017/V2RayA] 连接出现exit code: 127 (#4)


 
你好，我这里可以运行这个配置，请查看20170-20172端口是否被其他程序占用
 
sudo netstat -nlp | grep 2017
  
好的，我下午回去试试，如果是端口占用，我要怎么改动，是要改动config.json文&#x4EF6;，还是在v2raya中设置进行修改？
 
&mdash;

**Comment by RebornL** [comment]
> 查看是什么程序占用了端口，能否解决冲突，如果不行的话暂时只能通过修改v2raya服务端源代码解决，其后我会实现修改端口的功能。------------------ 原始邮件 ------------------ 发件人: "RebornL"<notifications@github.com> 发送时间: 2019年11月23日(星期六) 中午1:20 收件人: "mzz2017/V2RayA"<V2RayA@noreply.github.com>; 抄送: "mzz"<m@mzz.pub>;"Comment"<comment@noreply.github.com>; 主题: Re: [mzz2017/V2RayA] 连接出现exit code: 127 (#4) 你好，我这里可以运行这个配置，请查看20170-20172端口是否被其他程序占用 sudo netstat -nlp | grep 2017 好的，我下午回去试试，如果是端口占用，我要怎么改动，是要改动config.json文&#x4EF6;，还是在v2raya中设置进行修改？ &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好像与端口无关，似乎v2ray没有启动成功
![Screenshot from 2019-11-23 18-00-01](https://user-images.githubusercontent.com/13940893/69476951-312a8f00-0e1b-11ea-843b-f6b4b4c58954.png)

**Comment by RebornL** [comment]
> 查看是什么程序占用了端口，能否解决冲突，如果不行的话暂时只能通过修改v2raya服务端源代码解决，其后我会实现修改端口的功能。------------------ 原始邮件 ------------------ 发件人: "RebornL"<notifications@github.com> 发送时间: 2019年11月23日(星期六) 中午1:20 收件人: "mzz2017/V2RayA"<V2RayA@noreply.github.com>; 抄送: "mzz"<m@mzz.pub>;"Comment"<comment@noreply.github.com>; 主题: Re: [mzz2017/V2RayA] 连接出现exit code: 127 (#4) 你好，我这里可以运行这个配置，请查看20170-20172端口是否被其他程序占用 sudo netstat -nlp | grep 2017 好的，我下午回去试试，如果是端口占用，我要怎么改动，是要改动config.json文&#x4EF6;，还是在v2raya中设置进行修改？ &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我修改了v2ray.service中v2ray的具体执行路径为/usr/bin/v2ray/v2ray/v2ray之后，v2ray正常启动了
![Screenshot from 2019-11-23 18-11-22](https://user-images.githubusercontent.com/13940893/69477082-f0337a00-0e1c-11ea-8e83-5c0d02598c72.png)

**Comment by RebornL** [comment]
请问这个问题该怎么解决？ @mzz2017

**Comment by mzz2017** [comment]
下个版本会输出详细出错原因，你也可以加电报@mzz2017方便协助你第一时间解决问题

**Comment by RebornL** [comment]
> 下个版本会输出详细出错原因，你也可以加电报@mzz2017方便协助你第一时间解决问题

好的，那我等一个版本，把详细信息上传上来

**Comment by mzz2017** [comment]
你好，新版本已发布

**Comment by RebornL** [comment]
> 你好，新版本已发布

好的，现在更新

**Comment by RebornL** [comment]
> 你好，新版本已发布

显示的是“检测到v2ray-core可能未正确安装，请检查”，可能是我的v2ray-core不知道为什么安装的时候多了一个v2ray文件夹，变成v2ray/v2ray/v2ray/下才有v2ray可执行文件

**Comment by mzz2017** [comment]
你好，系统中使用的是systemctl还是service管理服务呢

**Comment by mzz2017** [comment]
麻烦打印一下sudo systemctl list-unit-files v2ray.service|grep v2ray.service

**Comment by RebornL** [comment]
> 麻烦打印一下sudo systemctl list-unit-files v2ray.service|grep v2ray.service

重装修改好了
![Screenshot from 2019-11-26 17-26-47](https://user-images.githubusercontent.com/13940893/69616655-f2424680-1071-11ea-8ed8-47335e5b5691.png)

但是现在显示的permission denied，没有权限执行v2ray

**Comment by mzz2017** [comment]
按理说v2raya应该正确运行在su状态呀，打印一下`sudo ps -ef|grep v2raya`以及`systemctl statsu v2raya`看看呢

**Comment by RebornL** [comment]
> 按理说v2raya应该正确运行在su状态呀，打印一下`sudo ps -ef|grep v2raya`以及`systemctl statsu v2raya`看看呢

![Screenshot from 2019-11-26 17-41-05](https://user-images.githubusercontent.com/13940893/69617924-f2434600-1073-11ea-8151-c9f36382cf76.png)

**Comment by mzz2017** [comment]
好的，我找台ubuntu调试一下，谢谢

**Comment by RebornL** [comment]
> 好的，我找台ubuntu调试一下，谢谢

如何？有结果吗？是我安装deb的方式不对吗？

**Comment by mzz2017** [comment]
你好，这个问题已经找到了，是ubuntu的/bin/sh不支持type的-p参数，目前在解决ubuntu上存在的其他问题，以及设置在网关时透明代理存在的问题

**Comment by mzz2017** [comment]
你好，这个问题已经找到了，ubuntu的 /bin/sh不支持type的-p参数，目前在适配出现在ubuntu的其他问题

**Comment by RebornL** [comment]
> 你好，这个问题已经找到了，ubuntu的 /bin/sh不支持type的-p参数，目前在适配出现在ubuntu的其他问题

好的， 谢谢！辛苦了^^

**Comment by mzz2017** [comment]
已更新

**Comment by RebornL** [comment]
> 已更新

软件可以正常连接了，但是为什么这样配置没办法上网


![Screenshot from 2019-11-27 09-28-32](https://user-images.githubusercontent.com/13940893/69685859-d46bf480-10f8-11ea-9892-ffca6a75846d.png)

**Comment by mzz2017** [comment]
![image](https://user-images.githubusercontent.com/30586220/69686747-9f14d600-10fb-11ea-9f78-b48e31cb6091.png)
你好，ubuntu 16.04使用正常，请问节点在非全局代理下是否正常使用？

**Comment by RebornL** [comment]
> ![image](https://user-images.githubusercontent.com/30586220/69686747-9f14d600-10fb-11ea-9f78-b48e31cb6091.png)
> 你好，ubuntu 16.04使用正常，请问节点在非全局代理下是否正常使用？
我的是Ubuntu18.04，我单独重新启动使用v2ray，使用网络设置的proxy可以正常使用
![Screenshot from 2019-11-27 10-04-35](https://user-images.githubusercontent.com/13940893/69687298-5f4eee00-10fd-11ea-8ace-e825140b7aae.png)



> ![image](https://user-images.githubusercontent.com/30586220/69686747-9f14d600-10fb-11ea-9f78-b48e31cb6091.png)
> 你好，ubuntu 16.04使用正常，请问节点在非全局代理下是否正常使用？

我的是Ubuntu18.04，我单独使用v2ray，使用网络设置的proxy可以正常使用
![Screenshot from 2019-11-27 10-04-35](https://user-images.githubusercontent.com/13940893/69687298-5f4eee00-10fd-11ea-8ace-e825140b7aae.png)

**Comment by mzz2017** [comment]
我找台18试一试------------------ 原始邮件 ------------------
发件人: "RebornL"<notifications@github.com>
发送时间: 2019年11月27日(星期三) 上午10:10
收件人: "mzz2017/V2RayA"<V2RayA@noreply.github.com>;
抄送: "mzz"<m@mzz.pub>;"Mention"<mention@noreply.github.com>;
主题: Re: [mzz2017/V2RayA] 连接出现exit code: 127 (#4)


 

 你好，ubuntu 16.04使用正常，请问节点在非全局代理下是否正常使用？
 我的是Ubuntu18.04，我单独重新启动使用v2ray，使用网络设置的proxy可以正常使用
 
   

 你好，ubuntu 16.04使用正常，请问节点在非全局代理下是否正常使用？
  
我的是Ubuntu18.04，我单独使用v2ray，使用网络设置的proxy可以正常使用
 
 
&mdash;

**Comment by mzz2017** [comment]
![image](https://user-images.githubusercontent.com/30586220/69747655-bc8c8300-1181-11ea-9aa3-b65c2276280d.png)

复现失败了……

**Comment by RebornL** [comment]
> ![image](https://user-images.githubusercontent.com/30586220/69747900-2a38af00-1182-11ea-9906-9fec8bed87e4.png)
> 
> 复现失败了……

哈哈哈太奇怪了，辛苦了，等我过段时间在研究一下v2ray使用方式

**Comment by mzz2017** [comment]
你好，已找到原因，是v2ray版本过低的原因，已添加版本提示，可以根据最新的README对v2ray和v2raya进行升级

**Comment by RebornL** [comment]
> 你好，已找到原因，是v2ray版本过低的原因，已添加版本提示，可以根据最新的README对v2ray和v2raya进行升级

好的，辛苦了，今晚更新一下试试
