### ISSUE TITLE
[BUG] 安装脚本取消-s参数以后显示以下错误

### ISSUE THREAD

**Issue by 857487** [mzz2017/V2RayA#40]
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-1017-raspi2 aarch64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Feb 15 15:29:14 UTC 2020

  System load:  0.04              Processes:           122
  Usage of /:   2.8% of 57.35GB   Users logged in:     0
  Memory usage: 29%               IP address for eth0: 192.168.8.102
  Swap usage:   0%

0 packages can be updated.
0 updates are security updates.

Your Hardware Enablement Stack (HWE) is supported until April 2023.

Last login: Sat Feb 15 14:43:06 2020 from 192.168.8.101
ubuntu@ubuntu:~$ curl -L https://github.com/mzz2017/V2RayA/raw/master/install/go.sh | sudo -E bash -s - --source ustc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   135  100   135    0     0    125      0  0:00:01  0:00:01 --:--:--   125
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
ubuntu@ubuntu:~$

**Comment by mzz2017** [comment]
国内环境屏蔽了raw.githubusercontent.com，我目前在推进jsdelivr的cdn，下周三之后我会解决这个安装问题。
相关 #36

**Comment by mzz2017** [comment]
当前的话如果上述域名被墙，需要自己找办法安装v2ray-core了

**Comment by 857487** [comment]
已解决安装v2ray-core的问题，我有个想法就是主路由用ROS，在ROS上建立域名规则，凡是指定的域名流量包括DNS解析全部走树莓派做的透明代理，请问这样可以实现吗?

**Comment by mzz2017** [comment]
可以尝试一下

**Comment by mzz2017** [comment]
已将安装过程使用cdn.jsdelivr.net加速
