### ISSUE TITLE
[BUG] 群晖完成安装后连接节点报错，ip地址问题？

### ISSUE THREAD

**Issue by adorff** [mzz2017/V2RayA#41]
**描述问题**
群晖docker安装后连接节点报错

详见附图
![批注 2020-02-16 102710](https://user-images.githubusercontent.com/36260326/74598154-35c3b400-50a7-11ea-8518-48d6ea788ec0.png)

**Comment by mzz2017** [comment]
看起来不支持TPORXY的透明代理，等待TODO：

- [ ]  透明代理重定向备选方案

**Comment by mzz2017** [comment]
已推master，可自行编译替换掉`/usr/bin/v2raya`后重启服务

**Comment by mzz2017** [comment]
可尝试v0.6.6.1版本

**Comment by adorff** [comment]
关闭全局透明代理可以连接，20171成功20172不行

**Comment by adorff** [comment]
20172 chrom+switchyomega可以；ios上代理不通，只能20171
