### ISSUE TITLE
我有v2ray账号怎么用这个工具科学上网呢

### ISSUE THREAD

**Issue by TouchDeeper** [mzz2017/V2RayA#42]
## 预期的行为和实际行为

> 如果是feature建议，请写在这里
请问我已经有v2Ray的账号了，在windows下也能使用v2RayN进行科学上网，如何用v2RayA在ubuntu上科学上网呢？

## 重现问题的步骤

> 如果条件允许请附图。如果是feature建议，请省略。

**Comment by mzz2017** [comment]
请详细描述问题

**Comment by TouchDeeper** [comment]
emmm,就是我已经在ubuntu上安装好v2RayA了，不知道如何下手，我看wiki也没有相关配置账号的教程呢

**Comment by mzz2017** [comment]
访问https://v2raya.mzz.pub，新建服务器或导入链接

**Comment by TouchDeeper** [comment]
我进入网站，要我设置服务器地址，我设置了一个我账号里的一个地址，不知道怎么进行下去
![image](https://user-images.githubusercontent.com/39310744/74601060-8998c200-50d4-11ea-80c0-0ce565bb1062.png)
![image](https://user-images.githubusercontent.com/39310744/74601103-f613c100-50d4-11ea-80f1-e2152b3a9ae9.png)

**Comment by mzz2017** [comment]
```bash
journalctl -u v2raya | tail -n 50
```
查看日志

**Comment by TouchDeeper** [comment]
输出为：
`-- No entries --`

**Comment by mzz2017** [comment]
> 输出为：
> `-- No entries --`

你是通过什么方式安装的v2raya

**Comment by TouchDeeper** [comment]
我用的是可执行文件：V2RayA_linux_amd64_v0.6.6

**Comment by mzz2017** [comment]
> 我用的是可执行文件：V2RayA_linux_amd64_v0.6.6

运行日志是什么

**Comment by TouchDeeper** [comment]
啊，我知道了，是要用运行V2RayA_linux_amd64_v0.6.6后输出的那个地址进去网页，我现在可以上了，请问这个设置怎么设置会比较快呢？我这样可以吗？
![2020-02-16 18-43-54屏幕截图](https://user-images.githubusercontent.com/39310744/74603231-624def00-50ec-11ea-817a-3def5f9e163d.png)

**Comment by TouchDeeper** [comment]
另外再请教下用这个工具终端怎么科学上网呢？

**Comment by mzz2017** [comment]
开启透明代理就可以终端上网了

**Comment by TouchDeeper** [comment]
ping www.google.com　貌似不行
用 curl www.google.com　好像就可以
![image](https://user-images.githubusercontent.com/39310744/74603559-a55d9180-50ef-11ea-8486-40165afc82e3.png)

还有我的这个设置可以吗？
![2020-02-16 18-43-54屏幕截图](https://user-images.githubusercontent.com/39310744/74603231-624def00-50ec-11ea-817a-3def5f9e163d.png)

**Comment by mzz2017** [comment]
可以。
ping是icmp协议，不走代理。

**Comment by TouchDeeper** [comment]
好的．谢谢你啦，谢谢你开发的工具！
