### ISSUE TITLE
[help] 

### ISSUE THREAD

**Issue by s1711880582** [mzz2017/V2RayA#44]
> 描述问题：
debian 9 安装报错，请问一下是我这边出现问题了吗？
在此描述问题

Err:1 https://apt.v2raya.mzz.pub v2raya/main i386 v2raya i386 0.6.6
  404  Not Found
E: Failed to fetch https://apt.v2raya.mzz.pub/pool/main/v/v2raya/v2raya_0.6.6_i386.deb  404  Not Found

root@OMV:~# sudo apt-get install v2raya
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  linux-image-4.9.0-9-686-pae
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  v2raya
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 11.0 MB of archives.
After this operation, 21.7 MB of additional disk space will be used.
Err:1 https://apt.v2raya.mzz.pub v2raya/main i386 v2raya i386 0.6.6
  404  Not Found
E: Failed to fetch https://apt.v2raya.mzz.pub/pool/main/v/v2raya/v2raya_0.6.6_i386.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

> V2RayA运行日志（Optional）：
>
> ```bash
> # daemon mond
> journalctl -u v2raya | tail -n 50
> 
> # docker mode
> docker logs v2raya_backend
> ```

在此贴入运行日志

**Comment by mzz2017** [comment]
刚进行了版本迭代
```bash
apt-get update
apt-get install v2raya
```

**Comment by s1711880582** [comment]
十分感谢回复。刚刚进行了安装，安装后发现端口没有启用，网页的demo也连接不上。
[口语.txt](https://github.com/mzz2017/V2RayA/files/4209869/default.txt)
不知道我需要抓取什么信息反馈给您。

**Comment by mzz2017** [comment]
v2ray-core安装了吗，systemctl status v2ray

**Comment by mzz2017** [comment]
telegram  https://t.me/joinchat/Lci6NVWB-x0Htm_woS6frA

**Comment by mzz2017** [comment]
我已看了你的日志
```bash
# 启动v2raya
systemctl start v2raya
# 开机自启
systemctl enable v2raya
```

**Comment by greendesert** [comment]
你好，我刚刚试试install 这个app， 但是不会的， E: Unable to locate package v2raya
 那怎么办那？
