### ISSUE TITLE
[help] V2RayA支持armhf构架的树莓派4B么？

### ISSUE THREAD

**Issue by dhobii** [mzz2017/V2RayA#45]
[help] V2RayA支持armhf构架的树莓派4B么？

**Comment by zhufengning** [comment]
releases 里有 arm64 的 deb 包，你可以试试

**Comment by mzz2017** [comment]
查看arm二进制文件是否可用，如可用，我可对deb重新打包一个armhf架构

**Comment by dhobii** [comment]
V2RayA_linux_arm_v0.6.7.1可运行，麻烦生成armhf的deb，谢谢。

**Comment by mzz2017** [comment]
https://github.com/mzz2017/V2RayA/releases/tag/v0.6.7.1
