### ISSUE TITLE
如何关闭服务端

### ISSUE THREAD

**Issue by Yuan-Quan** [mzz2017/V2RayA#47]
### 描述问题：
我想要重置账号密码
我忘记了我的密码, 需要删除/etc/v2ray/v2raya.json
但需要先停止v2raya以删除.
我已经尝试过移除v2raya, 重启, 但都无用

系统: manjaro kde
第一次使用Linux, 在阅读了wiki和进行了google之后仍无法解决问题, 向大佬请教

**Comment by mzz2017** [comment]
```
# 开机自启
systemctl enable v2raya

# 取消自启
systemctl disable v2raya

# 启动服务
systemctl restart v2raya

# 停止服务
systemctl stop v2raya

# 重启服务
systemctl restart v2raya
```

**Comment by mzz2017** [comment]
重启机器也可

**Comment by mzz2017** [comment]
你是说删除不了v2raya.json是吗，请以sudo权限/root用户删除

**Comment by Yuan-Quan** [comment]
感谢大佬帮助, 
在root 或sudo下,rm -rf时仍然显示 `permission denied`
但是在`systemctl stop v2raya`之后很顺利的删除了
