### ISSUE TITLE
[help] Exit Status 5

### ISSUE THREAD

**Issue by WIll-Xu35** [mzz2017/V2RayA#48]
### 版本、安装方式、系统

1. 你在使用什么版本的V2RayA
    0.6.7.1
2. 你通过什么方式安装V2RayA
    releases中的amd64 pkg文件，通过terminal sudo启动
3. 你所使用的操作系统、CPU架构
    ubuntu18.04 amd64

### 描述问题：

sudo运行pkg后，在网页端打开ui界面，提示v2raya可能没有正确安装。然后添加服务器信息之后，点击connect显示‘exit status 5’。systemctl中没有v2raya的服务。

### V2RayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```

没有查询到日志，terminal中的输出只显示了Connect: begin和Connect: doen

**Comment by mzz2017** [comment]
二进制运行方式不会有服务产生，这不是推荐的方法。
问题出现的原因应该是v2ray未安装。
通过systemctl status v2ray确认。
ubuntu建议通过软件源安装，详情见wiki

**Comment by WIll-Xu35** [comment]
跟着wiki成功安装v2ray，确认v2ray的服务已经起了。但是apt-get安装v2raya之后，v2raya.service一直是failed的状态

![Screenshot from 2020-02-24 12-27-05](https://user-images.githubusercontent.com/40563560/75128874-460c0c80-5701-11ea-9e81-2627c9fe46f1.png)

**Comment by mzz2017** [comment]
journalctl -u v2raya | tail -n 50

看一下日志

**Comment by WIll-Xu35** [comment]
看到是端口被占用了，之前sudo起的pkg在后台没有停，停了之后start一下服务就ok了～谢谢～
