### ISSUE TITLE
[BUG] manjaro通过yay安装

### ISSUE THREAD

**Issue by shizeying** [mzz2017/V2RayA#5]
出现的问题：
==> 警告： 使用现存的 $srcdir/ 树
==> 正在删除现存的 $pkgdir/ 目录...
==> 正在开始 build()...
go: github.com/PuerkitoBio/goquery@v1.5.0: Get https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.5.0.mod: dial tcp 172.217.27.145:443: i/o timeout
==> 错误： 在 build() 中发生一个错误。
    正在放弃...
Error making: v2raya

安装的方式
yay -S v2raya

请给出一个解决方式

**Comment by mzz2017** [comment]
`export GOPROXY=https://goproxy.io`
然后再试

**Comment by mzz2017** [comment]
你使用的是proxy.golang.org作为GOPROXY，但是看上去好像不太妙

**Comment by shizeying** [comment]
https://v2raya.mzz.pub/加载太久怎么解决呢

**Comment by mzz2017** [comment]
使用了pwa，第二次访问就秒开了

**Comment by shizeying** [comment]
这个网址指到的是本地吗？还是哪里呢

**Comment by mzz2017** [comment]
可以在设置-地址与端口中设置

**Comment by shizeying** [comment]
设置的位置在哪个地方呢？我刚才ping了下.pub那个网址，看到是走的一个cdn加速呢

**Comment by mzz2017** [comment]
界面右上角
