### ISSUE TITLE
安装后正常使用一旦重启后就会无法使用

### ISSUE THREAD

**Issue by lemon5227** [mzz2017/V2RayA#50]
### 版本、安装方式、系统

1. amd64 0.6.7.1 V2RayA

2. 你通过deb安装V2RayA

3. deepin x86 64位

### 描述问题

安装后正常使用但是重启后就会无法使用
显示未检测到v2reyA的服务端

### V2RayA运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志



```

### 截图

![74601060-8998c200-50d4-11ea-80c0-0ce565bb1062](https://user-images.githubusercontent.com/45664738/75291496-4caf9680-585d-11ea-8fd0-a849982304d3.png)

**Comment by mzz2017** [comment]
`systemctl enable v2raya`

**Comment by lemon5227** [comment]
问题解决了 感谢你的软件和你的帮助
