### ISSUE TITLE
docker-compose安装到第六步就不行了，挂代理也不行

### ISSUE THREAD

**Issue by siwday** [mzz2017/V2RayA#51]
### 版本、安装方式、系统

1. 你在使用docker-compose版本的V2RayA

2. 通过docker-compose安装V2RayA

3. manjaro和omv最新版，64位处理器

### 描述问题：

docker-compose安装不了

### V2RayA运行日志（Optional）：

Step 6/13 : RUN go build -o V2RayA .
 ---> Running in c52503bbc871
go: github.com/matoous/go-nanoid@v1.1.0: parsing go.mod: go.mod:1: usage: go 1.23
ERROR: Service 'backend' failed to build: The command '/bin/sh -c go build -o V2RayA .' returned a non-zero code: 1

```

**Comment by mzz2017** [comment]
请重新git pull

**Comment by siwday** [comment]
我不是太懂，就是重新docker-compose up吗，还有这个是不是网络问题

**Comment by mzz2017** [comment]
你克隆了有bug的代码，这个bug已被修复，请重新clone

**Comment by siwday** [comment]
Digest: sha256:7b76bb96d2b2a4f7fa11c3ae714e5ccbd089f7fcee1b6afc0c60aba0145e6d65
Status: Downloaded newer image for v2fly/v2fly-core:latest
Creating v2raya_backend_1 ... done
Creating v2raya_v2ray_1   ... error

ERROR: for v2raya_v2ray_1  Cannot start service v2ray: OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/8961/ns/pid\" caused \"lstat /proc/8961/ns/pid: no such file or directory\"": unknown

ERROR: for v2ray  Cannot start service v2ray: OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/8961/ns/pid\" caused \"lstat /proc/8961/ns/pid: no such file or directory\"": unknown
ERROR: Encountered errors while bringing up the project.
大神，新问题

**Comment by mzz2017** [comment]
看起来像是不支持pid=host，你是什么系统和CPU

**Comment by siwday** [comment]
我电脑已经装过了，这个是准备在nas装，看看能不能搞成旁路由那样，不行就算了吧

**Comment by mzz2017** [comment]
试一下docker run
