### ISSUE TITLE
增加自定义类型的服务器支持

### ISSUE THREAD

**Issue by unpin** [mzz2017/V2RayA#52]
### 您想提出的功能特性是否和现有问题相关？

目前 web 上服务器配置支持了 vmess, ss, ssr. 可否能增加一个自定义服务器支持？

### 功能特性内容

比如我想将 `outbounds` 里 `protocol` 配置成 `http`, 所有流量转发到 localhost 的 7890 端口，这样可以方便的使用 clash 定制路由规则。当前在 web 上无法直接完成。

**Comment by mzz2017** [comment]
这个是作为routingA（一种自定义路由格式）的一部分在日程的，不过需要时间。

为什么不直接使用clash呢，貌似clash也可以作系统代理。

**Comment by mzz2017** [comment]
v0.6.8已支持RoutingA <https://github.com/mzz2017/V2RayA/wiki/RoutingA>
