### ISSUE TITLE
如何删除掉？？？？

### ISSUE THREAD

**Issue by leyubook** [mzz2017/V2RayA#53]
### 版本、安装方式、系统

1. 你在使用什么版本的V2RayA
最新
2. 你通过什么方式安装V2RayA
脚本
3. 你所使用的操作系统、CPU架构
debian10     64位

如何删除啊啊

### V2RayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志



```

**Comment by mzz2017** [comment]
通过`apt-get`安装的话，使用`apt-get remove v2raya`卸载

**Comment by mzz2017** [comment]
assume resolved
