### ISSUE TITLE
如何配置内网DNS

### ISSUE THREAD

**Issue by motecshine** [mzz2017/v2rayA#54]
平时需要连内网然后连公司跳板机工作， 我看config文件里的dns都是远端的，如何配置内网DNS

**Comment by mzz2017** [comment]
问题在于有些域名只有内网dns有内网ip的dns记录，而公网dns没有记录？

**Comment by motecshine** [comment]
@mzz2017  对的 我们内网DNS 只负责解析内网域名，公网DNS肯定没记录，ssh 连域名跳板机的时候就会出现解不开内网域名的情况

**Comment by mzz2017** [comment]
> @mzz2017 对的 我们内网DNS 只负责解析内网域名，公网DNS肯定没记录，ssh 连域名跳板机的时候就会出现解不开内网域名的情况

所以使用场景是：
1. 你正在使用一个非内网IP
2. 你使用V2Ray或SS(R)经过V2RayA连接了一个国外服务器
3. 你希望能DNS解析到内网服务器的公网IP地址，以便通过SSH连接

是吗

**Comment by motecshine** [comment]
是的

**Comment by mzz2017** [comment]
目前暂时没有自定义dns的功能，你目前可以自行添加hosts达到目的。

**Comment by mzz2017** [comment]
现在可以使用0.7.0.2版本，将“防止DNS污染”设置为“关闭”，便会使用本机默认DNS

**Comment by mzz2017** [comment]
v0.7.1（gui及服务）选择仅防止dns劫持，点击配置，可自定义dns
