### ISSUE TITLE
服务器地址为ip自动设置证书域名

### ISSUE THREAD

**Issue by fuck2ky** [mzz2017/V2RayA#56]
### 您想提出的功能特性是否和现有问题相关？

最近在用的机场用上了百度云中转，如果入站接接受的不是域名需要手动配置服务端证书域名，比如像这样
```json
{
    "outbounds": [
        {
          "tag": "proxy",
          "protocol": "vmess",
          "settings": {
            "vnext": [
              {
                "address": "122.190.3.92",
                "port": 443,
                "users": [
                  {
                    "id": "xx",
                    "alterId": 1,
                    "security": "auto"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "ws",
            "security": "tls",
            "tlsSettings": {
              "allowInsecure": true,
              "serverName": null
            },
            "wsSettings": {
              "connectionReuse": true,
              "path": "/admin",
              "headers": {
                "Host": "github.com"
              }
            }
          }
        }
      ]
}
```

### 功能特性内容

希望服务端证书域名能自动设置为WebSocket配置里的域名

**Comment by mzz2017** [comment]
需要手动设置tls的serverName是吧

**Comment by Justsoos** [comment]
不止这个字段，实际上，来自v2rayN的简单 vmess:// 对大多数特殊字段配置都不支持。
这也是说为啥最好开放 config.json 可以直接编辑的能力
实际上，开放后，用户直接可以自己加入 socks5，http 上游代理

v2ray core 本身这些都已经支持

**Comment by mzz2017** [comment]
> 实际上，开放后，用户直接可以自己加入 socks5，http 上游代理

我想你要的是[RoutingA]
(https://github.com/mzz2017/V2RayA/wiki/RoutingA)

**Comment by Justsoos** [comment]
并不是路由级别的上下游，而是直接修改 config.json 的能力 ，也就是 v2ray-core 在命令行直接执行的那个配置文件。
由于 v2ray core 的自由度过高，很多 v2ray 的服务器配置是不能在只有5，6个固定变量的 vmess:// 里表达出来的。

**Comment by Justsoos** [comment]
比如这个 issue，由于代码不对头，改了三个版本的 v2rayU， 现在还只能通过直接手动改 config.json 来使用 socks5 的上游代理。

https://github.com/yanue/V2rayU/issues/306

**Comment by mzz2017** [comment]
我认为高度手动化的配置不是这类工具应该做的，高级用户确实可以自己修改config.json文件达到目的

如果可以自己修改config.json，工具又何必存在呢

如果是为了测速或透明代理，完全可以使用其他工具帮助完成

**Comment by Justsoos** [comment]
并不是这样理解，作为可用的 v2ray 客户端，由于 v2ray 的特殊性质，都给用户留了直接修改 config.json 的能力，或者至少方便性。

**Comment by Justsoos** [comment]
另外，说一下 v2rayN 开始定义的这个 vmess:// URI 的定义，实际上都来自这里：
[https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))

这是 v2ray 使用早期比较常用的几个传递参数，但实际上最近应用的已经远远超越这个 vmess 可以涵盖的内容了。比如非常常用的楼主提到的 server name和host都需要特别定义的伪装。

**Comment by mzz2017** [comment]
fixed

**Comment by fuck2ky** [comment]
> fixed

ip已经好了，最近发现域名也不行，而且现在连接到这种节点后会经常提示 **Fail in connecting: v2ray-core does not start normally, there may be a problem with the configuration file or the required port is occupied**，端口没被占用， v2raya会显示没连接任何一个节点，实际已经连接了。

**Comment by mzz2017** [comment]
1. 上个版本有这样的问题吗
2. 提示失败，但是节点**切换**确实成功了吗




mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: fuck2ky <notifications@github.com&gt;
发送时间: 2020年3月28日 11:59
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: mzz <m@mzz.pub&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] 服务器地址为ip自动设置证书域名 (#56)





  
fixed
  
ip已经好了，最近发现域名也不行，而且现在连接到这种节点后会经常提示 Fail in connecting: v2ray-core does not start normally, there may be a problem with the configuration file or the required port is occupied，端口没被占用， v2raya会显示没连接任何一个节点，实际已经连接了。

**Comment by fuck2ky** [comment]
1 以前也不行，最近机场更新才发现其实域名也不行

2 测试了一下发现是新版的问题，实际上已经切换到新节点但是v2raya会提示连接失败并且没连接节点

![1](http://p9.pstatp.com/large/pgc-image/e82c905e96384f009ef64e2efde2f774)

![2](http://p1.pstatp.com/large/pgc-image/677373c143114009a541a4c12abb878c)

![3](http://p1.pstatp.com/large/pgc-image/b85096cc50cb4ed3a945929384d7c758)

**Comment by mzz2017** [comment]
是用docker的吗

**Comment by fuck2ky** [comment]
> 是用docker的吗
不是

**Comment by mzz2017** [comment]
v0.6.8.4已修复

**Comment by fuck2ky** [comment]
有种情况是服务器地址可能是另一个域名，我觉得设置SNI这里应该改成这样
```go
// if v.add no equal v.host and host is not empty, set SNI
if v.Host != "" && v.Host != v.Add {
	o.StreamSettings.TLSSettings.ServerName = v.Host
}
```

**Comment by mzz2017** [comment]
挺有道理的，你可以提PR，或者下个版本我会修改。


mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: fuck2ky <notifications@github.com&gt;
发送时间: 2020年3月29日 22:36
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: mzz <m@mzz.pub&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] 服务器地址为ip自动设置证书域名 (#56)





 
有种情况是服务器地址可能是另一个域名，我觉得设置SNI这里应该改成这样
 // if v.add no equal v.host and host is not empty, set SNI if v.Host != "" &amp;&amp; v.Host != v.Add { o.StreamSettings.TLSSettings.ServerName = v.Host }

**Comment by mzz2017** [comment]
v0.6.8.5已发布
