### ISSUE TITLE
断流问题

### ISSUE THREAD

**Issue by xfdywy** [mzz2017/v2rayA#58]
### 版本、安装方式、系统

1. 你在使用什么版本的V2RayA
更新到最新版了

2. 你通过什么方式安装V2RayA
软件源安装

3. 你所使用的操作系统、CPU架构
操作系统 deepin 15.11

### 描述问题
多次断流。就是用着好好的就无法翻墙了，比如youtube看到一半就连接不上了，重新开新的浏览器窗口也上不去谷歌youtube了，必须要断开当前的服务器，然后重新连一下。有时候间隔一分钟断一次，有时候几分钟断一次。

为了证明是断流不是我服务器的问题，我连着服务器看youtube，或者刷网页，然后没法翻墙之后，我直接用web gui 上面的http测速功能测速，这个功能应该是会断开当前连接，然后重新连接测，我的youtube就可以重新打开了，google网页也可以打开了。

### V2RayA运行日志：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志



```

**Comment by mzz2017** [comment]
你用的是什么节点类型，是ssr吗

**Comment by xfdywy** [comment]
v2ray

**Comment by mzz2017** [comment]
v2ray使用的是标准v2ray-core实现，V2RayA只做了配置速配及透明代理，如果你在关闭透明代理后，仅使用端口来达到代理目的，仍出现这种情况，则考虑是v2ray-core的问题。

**Comment by xfdywy** [comment]
好的。我开着透明代理。我有空试一下关闭透明代理，看还存不存在这个问题。谢谢

**Comment by mzz2017** [comment]
issue长期无回应，假定已解决
