### ISSUE TITLE
[BUG] 无法打开wsj.com，可以ping但是无法访问

### ISSUE THREAD

**Issue by sherpahu** [mzz2017/V2RayA#6]
**描述问题**
在代理模式、大陆白名单模式下可以访问谷歌、youtube、纽约时报等网站，但是就是打不开wsj.com。
在终端可以ping通wsj.com，但是`curl wsj.com`显示如下错误
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.wsj.com:443 `
![image](https://user-images.githubusercontent.com/30852287/69767808-f75ddd80-11b8-11ea-8c8b-6e7b17a35db8.png)

在clash下使用v2ray的同一个节点可以访问，应该不是节点的问题。

**复现问题的步骤**
使用代理模式或者大陆白名单访问wsj.com
在终端`ping wsj.com` `curl wsj.com`

**截图**
![image](https://user-images.githubusercontent.com/30852287/69767867-2f652080-11b9-11ea-8d01-05c2ea7fadc9.png)
可以在截图中看到谷歌访问正常，但是wsj.com无法打开

**Comment by mzz2017** [comment]
你好，我这里在手机上使用小火箭也不能访问。
后面会进一步排查问题。

**Comment by sherpahu** [comment]
好的，感谢

**Comment by sherpahu** [comment]
现在貌似有可以打开了，玄学

**Comment by sherpahu** [comment]
好像还是只有华尔街日报打不开，真的很奇怪

**Comment by mzz2017** [comment]
![image](https://user-images.githubusercontent.com/30586220/69962671-72245100-1549-11ea-8768-b770f83bb198.png)
![image](https://user-images.githubusercontent.com/30586220/69962688-79e3f580-1549-11ea-855d-e0482b1a2acf.png)

你好，我这里是可以正常访问的，只是感觉是要慢一点。

1. 使用的是什么设置
2. clash是可以的吗？

**Comment by sherpahu** [comment]
我再多尝试了一些方法，问题得到了解决，应该是我没有配置系统的socks代理导致的。
我之前没有设置socks代理为127.0.0.1:20170的时候的确是能够登上谷歌、纽约时报、youtube使用git clone速度也明显比在墙内快，但是华尔街日报、Ins却无法访问。
![image](https://user-images.githubusercontent.com/30852287/69964455-6c306f00-154d-11ea-9d77-a2d47f56c3f5.png)
我对透明代理的原理的理解有点不到位，我不是很懂为什么已经使用透明代理了还需要配置socks代理端口？而在不配置或不正确配置的时候有部分网站又能够正常翻墙访问？而在正确设置之后访问华尔街日报明显感觉延迟变高，在youtube上测速又跟clashr（clash的改良版，可以使用ssr）下是一致的？
我之前找到过一些关于透明代理的介绍，其中有如下表述：
>  什么是透明代理？
在正向代理中，一个软件如果想走 client 的代理服务，我们必须显式配置该软件，对该软件来说，有没有走代理是很明确的，大家都“心知肚明”。而透明代理则与正向代理相反，当我们设置好合适的防火墙规则（仅以 Linux 的 iptables 为例），我们将不再需要显式配置这些软件来让其经过代理或者不经过代理（直连），因为这些软件发出的流量会自动被 iptables 规则所处理，那些我们认为需要代理的流量，会被通过合适的方法发送到 client 进程，而那些我们不需要代理的流量，则直接放行（直连）。这个过程对于我们使用的软件来说是完全透明的，软件自身对其一无所知。这就叫做 透明代理。注意，所谓透明是对我们使用的软件透明，而非对 client、server 或目标网站透明，理解这一点非常重要。
https://github.com/zfl9/ss-tproxy#什么是透明代理

所以我就没有配置像clashr一样的系统代理。

**Comment by mzz2017** [comment]
如果你不使用代理可以访问一些境外网站，可能是因为ipv6的原因，一些网站的ipv6的地址是没有被ban的。
另外V2RayA的透明代理高度依赖于v2ray-core，之前查明在低版本v2ray-core上透明代理甚至无法正常使用，高版本上的问题暂时没有探明，使用还算正常。所以按理说系统如果可以很方便设置系统代理且不需要作为网关为其他机器提供服务的话，可以用系统代理取代透明代理。
另外，可以告知v2ray的版本吗，找到v2ray的二进制文件，使用参数-version获取。一般用systemctl status v2ray可查。

**Comment by sherpahu** [comment]
我在校园网环境下有可能是ipv6的原因。至于说版本，我的系统在昨天被我又搞崩了暂时没法获知。但我能确定的是直接利用yay通过AUR安装的。

**Comment by mzz2017** [comment]
那应该最新了哈。我用的是manjaro，暂时感觉还行。

**Comment by sherpahu** [comment]
OK，感谢。（等我考完试在寒假再把Manjaro重装一次再进一步尝试一下，逃
