### ISSUE TITLE
v2ray_core更新到4.23.1后无法使用

### ISSUE THREAD

**Issue by Paraworker** [mzz2017/V2RayA#60]
### 版本、安装方式、系统

1. 你在使用什么版本的V2RayA
0.6.8.1

2. 你通过什么方式安装V2RayA
AUR

3. 你所使用的操作系统、CPU架构
Manjaro_Linux
amd64

### 描述问题：

v2ray_core更新到4.23.1后无法使用，节点(vmess)连接后所有网站均无法打开，CPU使用率偏高

### V2RayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志



```

**Comment by mzz2017** [comment]
这是v2ray-core已知bug，建议暂时降级，稍后我将进行修复。
