### ISSUE TITLE
无法启用TPROXY模块: the version of v2ray-core is lower than 4.19.1

### ISSUE THREAD

**Issue by DedSecer** [mzz2017/V2RayA#61]
### 版本、安装方式、系统

我是一个arch用户，
用的是从yay安装的最新版v2raya
我已经安装了shadowsock和v2ray软件包

### 描述问题：
我在启动v2raya时看到一条信息
无法启用TPROXY模块: the version of v2ray-core is lower than 4.19.1
我可以从浏览器连接v2raya GUI

但是我连接ssr节点的时候提示：Fail in connecting: v2ray-core does not start normally, there may be a problem with the configuration file or the required port is occupied

**Comment by mzz2017** [comment]
`v2ray -version`看一下

**Comment by DedSecer** [comment]
'v2ray --version':
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)

'journalctl -u v2raya|grep "V2Ray binary"|tail -n 1':
A unified platform for anti-censorship.

Mar 27 10:21:14 DS-pc v2raya[38235]: V2Ray binary is at /usr/bin/v2ray/v2ray

**Comment by mzz2017** [comment]
再执行`/usr/bin/v2ray/v2ray -version`看看

**Comment by DedSecer** [comment]
fish: The file “/usr/bin/v2ray/v2ray” is not executable by this user

？？这是什么问题

**Comment by mzz2017** [comment]
sudo一下呢

**Comment by DedSecer** [comment]
不是这个吧，是不是 '/usr/bin/v2ray/v2ray'

**Comment by mzz2017** [comment]
```bash
ls -lah /usr/bin/v2ray/v2ray
which v2ray
sudo /usr/bin/v2ray/v2ray -version
```

**Comment by DedSecer** [comment]
'/usr/bin/v2ray --version':
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)
A unified platform for anti-censorship.

**Comment by DedSecer** [comment]
ls: cannot access '/usr/bin/v2ray/v2ray': Not a directory

**Comment by DedSecer** [comment]
'which v2ray':
/usr/bin/v2ray

**Comment by mzz2017** [comment]
```bash
cat /usr/lib/systemd/system/v2ray.service
```

**Comment by DedSecer** [comment]
[Unit]
Description=V2Ray - A unified platform for anti-censorship
Documentation=https://v2ray.com https://guide.v2fly.org
After=network.target nss-lookup.target
Wants=network-online.target

[Service]
# If the version of systemd is 240 or above, then uncommenting Type=exec and commenting out Type=simple
#Type=exec
Type=simple
# Runs as root or add CAP_NET_BIND_SERVICE ability can bind 1 to 1024 port.
# This service runs as root. You may consider to run it as another user for security concerns.
# By uncommenting User=v2ray and commenting out User=root, the service will run as user v2ray.
# More discussion at https://github.com/v2ray/v2ray-core/issues/1011
User=root
#User=v2ray
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_NET_RAW
NoNewPrivileges=yes
ExecStart=/usr/lib/v2ray/v2ray -config /etc/v2ray/config.json
Restart=on-failure
# Don't restart in the case of configuration error
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target

**Comment by mzz2017** [comment]
我估计你这个问题是systemd服务没有reload

```bash
systemctl daemon-reload
```

**Comment by DedSecer** [comment]
"Mar 27 10:21:14 DS-pc v2raya[38235]: V2Ray binary is at /usr/bin/v2ray/v2ray"
我的 /usr/bin/v2ray不是一个文件夹，而是一个可执行文件可是上面说还有/usr/bin/v2ray/v2ray，是不是 这里的问题

**Comment by mzz2017** [comment]
不是这个问题，取得这个路径是从
`systemctl status v2ray|grep /v2ray.service`找到对应的v2ray.service然后读取ExecStart=相关的路径

**Comment by DedSecer** [comment]
已经解决了
我修改了v2ray.server文件中的ExecStart的值为/usr/bin/v2ray
谢谢
