### ISSUE TITLE
有用户反馈最新版本无法连接节点

### ISSUE THREAD

**Issue by mzz2017** [mzz2017/V2RayA#62]
有用户反馈在v0.6.8.4出现了无法连接节点的问题。

而另一部分用户反馈在v0.6.8.3出现了切换节点提示端口占用问题，而问题在v0.6.8.4得到解决。

如果你出现了类似上述两类用户的问题，可自行考虑安装版本。如需v0.6.8.3，软件源安装的用户可在[releases](https://github.com/mzz2017/V2RayA/releases/v0.6.8.3)中寻找安装包进行降级安装。

如你出现了类似问题，可提供详细信息帮助改进，或直接PR。

**Comment by u2333** [comment]
v0.6.8.4无法连接节点，提示 Error: Request failed with status code 500
日志出现 runtime error: slice bounds out of range[:-1]

**Comment by mzz2017** [comment]
详细日志有吗




mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: u2333 <notifications@github.com&gt;
发送时间: 2020年3月31日 08:23
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: mzz <m@mzz.pub&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] 有用户反馈最新版本无法连接节点 (#62)





 
v0.6.8.4无法连接节点，提示 Error: Request failed with status code 500
 日志出现 runtime error: slice bounds out of range[:-1]

**Comment by mzz2017** [comment]
已找到问题。
升级到v0.6.8.5即可。

**Comment by yishanchuan** [comment]
debian系统还是有问题，
报错也是Error: Request failed with status code 500。
已经更新到最新版本`v2raya is already the newest version (1.1.0).` 还是出错了，尝试过在浏览器直接访问URL，是成功的。请问怎么处理？
