### ISSUE TITLE
v2raya后台服务在运行 端口也没有报冲突，但是http检测和连接节点连不上

### ISSUE THREAD

**Issue by paladin4fan** [mzz2017/V2RayA#64]
系统是Manjaro 用yay安装的v2raya
一直连不上 手动kill了后端并在终端里手动运行
测试Http时终端输出如下
2020/03/31 17:26:40 socks5.go:87: [socks5] listening TCP on 127.0.0.1:14322
2020/03/31 17:26:56 [Warning] V2RayA/core/v2ray: v2ray-core does not start normally, there may be a problem with the configuration file or the required port is occupied
连接节点终端输出如下
2020/03/31 17:29:42 connect.go:28: Connect: begin
2020/03/31 17:29:57 connect.go:44: Connect: done
2020/03/31 17:29:57 [Warning] [Fail in connecting] > V2RayA/core/v2ray: v2ray-core does not start normally, there may be a problem with the configuration file or the required port is occupied
另外 刚打开webUI的时候页面提示v2raya服务正在运行 但是左上角是红色的未运行状态 此时点击这个按钮会提示cannot start V2Ray without server connected
但是链接节点又会如上所述报错
尝试过切换监听端口 无效

**Comment by mzz2017** [comment]
什么版本？

**Comment by liruoyu2008** [comment]
试试看把系统时间校对，我就碰过这样的问题


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: paladin4fan <notifications@github.com&gt;
发送时间: 2020年3月31日 17:35
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] v2raya后台服务在运行 端口也没有报冲突，但是http检测和连接节点连不上 (#64)






系统是Manjaro 用yay安装的v2raya
一直连不上 手动kill了后端并在终端里手动运行
测试Http时终端输出如下
2020/03/31 17:26:40 socks5.go:87: [socks5] listening TCP on 127.0.0.1:14322
2020/03/31 17:26:56 [Warning] V2RayA/core/v2ray: v2ray-core does not start normally, there may be a problem with the configuration file or the required port is occupied
连接节点终端输出如下
2020/03/31 17:29:42 connect.go:28: Connect: begin
2020/03/31 17:29:57 connect.go:44: Connect: done
2020/03/31 17:29:57 [Warning] [Fail in connecting] &gt; V2RayA/core/v2ray: v2ray-core does not start normally, there may be a problem with the configuration file or the required port is occupied
另外 刚打开webUI的时候页面提示v2raya服务正在运行 但是左上角是红色的未运行状态 此时点击这个按钮会提示cannot start V2Ray without server connected
但是链接节点又会如上所述报错
尝试过切换监听端口 无效

**Comment by mzz2017** [comment]
12345也不能被占用

**Comment by paladin4fan** [comment]
> 12345也不能被占用

重新启动过机子之后就可以正常连接了……
顺便请问一下 在webui里开启redir透明代理 是不是也会代理UDP链接呢

另外有个奇怪的地方 就是
KDE使用系统设置代理填localhost的http pac代理端口没用 要开redir透明代理才行
不知道是不是KDE自身的问题

**Comment by mzz2017** [comment]
会代理udp，但由于v2ray-core自身的问题，不能用来打游戏，只能用于正常上网。

**Comment by paladin4fan** [comment]
> 会代理udp，但由于v2ray-core自身的问题，不能用来打游戏，只能用于正常上网。
> 
> 因此即使是用系统设置的方式启用全局代理也不能用来打游戏。

多谢回复 那么想要添加自定义黑名单的话是不是只能把pac模式换成自定义路由呢

**Comment by mzz2017** [comment]
![image](https://user-images.githubusercontent.com/30586220/78024932-c02c5280-738b-11ea-8187-202c56aa8ae6.png)

RoutingA 更自由一点

**Comment by paladin4fan** [comment]
> ![image](https://user-images.githubusercontent.com/30586220/78024932-c02c5280-738b-11ea-8187-202c56aa8ae6.png)
> 
> RoutingA 更自由一点

好的 我尝试一下
