### ISSUE TITLE
v2raya-gui使用docker部署似乎不支持ARM64架构

### ISSUE THREAD

**Issue by RuofengX** [mzz2017/V2RayA#67]
问题环境：ARM64架构，armbian5.88，斐讯N1盒子

在斐讯N1盒子上部署了后端v2raya
使用Windows docker在Windows10上部署gui使用正常；
之后尝试在斐讯N1盒子上通过docker部署gui运行时报错：
`standard_init_linux.go:211: exec user process caused "exec format error"`

v2raya-gui是否不支持ARM64？

**Comment by mzz2017** [comment]
确实，当时没考虑到这个问题。
v2raya的docker镜像应该也会出现相同的问题。

------------------ 原始邮件 ------------------
发件人: RuofengX <notifications@github.com&gt;
发送时间: 2020年4月11日 11:41
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] v2raya-gui使用docker部署似乎不支持ARM64架构 (#67)





 
问题环境：ARM64架构，armbian5.88，斐讯N1盒子
 
在斐讯N1盒子上部署了后端v2raya
 使用Windows docker在Windows10上部署gui使用正常；
 之后尝试在斐讯N1盒子上通过docker部署gui运行时报错：
 standard_init_linux.go:211: exec user process caused "exec format error"
 
v2raya-gui是否不支持ARM64？

**Comment by RuofengX** [comment]
我想编译安装GUI，现在应该如何进行？

**Comment by mzz2017** [comment]
git clone xxx
进入gui目录
yarn
yarn run build将生成静态文件，在上一级的web目录
通过nginx等web服务器部署




mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: RuofengX <notifications@github.com&gt;
发送时间: 2020年4月11日 12:49
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: mzz <m@mzz.pub&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] v2raya-gui使用docker部署似乎不支持ARM64架构 (#67)





 
我想编译安装GUI，现在应该如何进行？

**Comment by mzz2017** [comment]
现mzz2017/v2raya-gui镜像已支持多种CPU架构

**Comment by RuofengX** [comment]
谢谢
