### ISSUE TITLE
在代理旁路由上部署GUI作为Web控制台

### ISSUE THREAD

**Issue by RuofengX** [mzz2017/v2rayA#69]
### 功能特性内容
需求是：在专门的旁路由上同时部署V2-Core组件、V2A-core组件以及GUI，并且把GUI的端口公开给局域网，让每一个设备都可以在Web界面上可视化地操作。现在的问题是，目前的GUI每次启动都是本地化的，而且每次启动后端的端口都是localhost:2017。
我希望这个GUI可以像正常的Webserver那样对所有用户提供无差别的服务，或者也可以添加一个默认地址端口，让他每次本地化的启动之后自动连接到局域网中的设备。

**Comment by mzz2017** [comment]
目前会将后端地址记录在浏览器，无痕模式将会出现你所说的问题。
你说的问题可以通过在gui中内嵌一个node或python服务，将数据保存在服务端来完成。这个feature等PR吧。




mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: RuofengX <notifications@github.com&gt;
发送时间: 2020年4月14日 10:50
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] 在代理旁路由上部署GUI作为Web控制台 (#69)





 
功能特性内容
 
需求是：在专门的旁路由上同时部署V2-Core组件、V2A-core组件以及GUI，并且把GUI的端口公开给局域网，让每一个设备都可以在Web界面上可视化地操作。现在的问题是，目前的GUI每次启动都是本地化的，而且每次启动后端的端口都是localhost:2017。
 我希望这个GUI可以像正常的Webserver那样对所有用户提供无差别的服务，或者也可以添加一个默认地址端口，让他每次本地化的启动之后自动连接到局域网中的设备。

**Comment by mzz2017** [comment]
不过可以有一个折中方案，当访问的gui地址是一个本地地址时默认设置后端地址为该ip




mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: RuofengX <notifications@github.com&gt;
发送时间: 2020年4月14日 10:50
收件人: mzz2017/V2RayA <V2RayA@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[mzz2017/V2RayA] 在代理旁路由上部署GUI作为Web控制台 (#69)





 
功能特性内容
 
需求是：在专门的旁路由上同时部署V2-Core组件、V2A-core组件以及GUI，并且把GUI的端口公开给局域网，让每一个设备都可以在Web界面上可视化地操作。现在的问题是，目前的GUI每次启动都是本地化的，而且每次启动后端的端口都是localhost:2017。
 我希望这个GUI可以像正常的Webserver那样对所有用户提供无差别的服务，或者也可以添加一个默认地址端口，让他每次本地化的启动之后自动连接到局域网中的设备。

**Comment by mzz2017** [comment]
> 不过可以有一个折中方案，当访问的gui地址是一个内网地址时默认设置后端地址为该ip

https://github.com/mzz2017/V2RayA/commit/27794cb7062e9e79a516766252976b4de1fc5c3d

已修复，使用最新image即可。
