### ISSUE TITLE
[BUG] 修改服务端地址之后无法连接

### ISSUE THREAD

**Issue by jsfaint** [mzz2017/V2RayA#7]
**描述问题**
通过web修改服务端地址之后，会出现如图提示
![image](https://user-images.githubusercontent.com/571829/69774026-9d1c4700-11cf-11ea-9fda-5bd6080c72d7.png)

看起来除了`localhost`和`127.0.0.1`以外的地址都无法工作。
即使指定的IP是本机的IP都不行

**复现问题的步骤**
修改服务端地址为localhost，127.0.0.1以外的其他地址

**预期结果**
支持远端服务器

**截图**
见描述问题

**Comment by mzz2017** [comment]
1. 请确保远端服务器开放了2017端口
2. 请不要在远端服务器使用全局透明代理，会导致ssh无法连接等问题，除非你和远端服务器在同一局域网。

**Comment by mzz2017** [comment]
这个修改地址的功能我已经在阿里云测试过了，完全可行的哈，本机ip不行可能是因为各种原因

**Comment by jsfaint** [comment]
收到~我再检查一下本地的环境。感谢

**Comment by mzz2017** [comment]
你好，我排查之后发现可能是这样的问题，由于v2raya的demo站是架在https上的，浏览器出于安全性，不会允许对http的资源进行post、put、delete，所以这里有两个解决方案仅供参考：
1. 将服务端配置在https
2. 手动前端部署在http
如果你选择第二种方案并自动部署，欢迎贡献出来作为V2RayA的http demo站点。

**Comment by mzz2017** [comment]
目前已添加http备用站点

http://v.mzz.pub

**Comment by mzz2017** [comment]
在远端服务器开启透明代理也已经有方案了，会在将来实现。

**Comment by jsfaint** [comment]
> 在远端服务器开启透明代理也已经有方案了，会在将来实现。

其实是想在路由器上跑来着……不过目前还没成功……

**Comment by mzz2017** [comment]
用http站点试试。
我也喜欢搞路由器，你那个是arm的吗？

**Comment by jsfaint** [comment]
> 用 http 站点试试。
> 我也喜欢搞路由器，你那个是 arm 的吗？

是arm的，小米路由2硬盘版
编译之后v2raya可以跑起来。但是提示说v2ray-core没有正确安装

**Comment by mzz2017** [comment]
> 是arm的，小米路由2硬盘版
> 编译之后v2raya可以跑起来。但是提示说v2ray-core没有正确安装

那你需要先在路由器上安装v2ray。要是安装起来是服务的话还好，要送没有服务的话，我还没开始测试非systemd环境呢，那就可能会有一些问题。

刚巧今天离开学校，新的生活环境应该暂时没有让我玩的arm路由器了。

**Comment by jsfaint** [comment]
> > 是 arm 的，小米路由 2 硬盘版
> > 编译之后 v2raya 可以跑起来。但是提示说 v2ray-core 没有正确安装
> 
> 那你需要先在路由器上安装 v2ray。要是安装起来是服务的话还好，要是没有服务的话，我还没开始测试非 systemd 环境呢，那就可能会有一些问题。
> 
> 刚巧今天离开学校，新的生活环境应该暂时没有让我玩的 arm 路由器了。

v2ray有安装，也在PATH下，但是没有systemd
v2raya目前需要systemd才能启动v2ray-core吗？
抱歉，我还没看v2raya的代码

**Comment by mzz2017** [comment]
本来是有计划支持你目前这种情况的，现在时间不是很充裕了，前段时间更新太猛，后面更新会稍微慢一些，有嫌我更新慢来不及的地方开源项目靠大家了😄。

**Comment by mzz2017** [comment]
那个提示是针对systemd的，你看看具体能不能用，因为有代码是对这种情况适配的，但不一定能work，我没怎么测过

**Comment by mzz2017** [comment]
你好，已支持路由器，可以根据[README](https://github.com/mzz2017/V2RayA#%E5%9C%A8%E8%B7%AF%E7%94%B1%E5%99%A8%E4%BD%BF%E7%94%A8)进行操作

**Comment by jsfaint** [comment]
昨晚抽时间在路由器上试了一下，已经可以认到v2ray的命令
还没成功用起来，看起来我的路由器kernel缺少tproxy。
不过与这个issue无关，这个issue我先关掉了。
谢谢

**Comment by mzz2017** [comment]
后期会添加第二方案，用于内核缺少tproxy时使用透明代理。

**Comment by jsfaint** [comment]
> 后期会添加第二方案，用于内核缺少 tproxy 时使用透明代理。

小米路由用mixbox没问题，怀疑可能我编译的v2ray有问题。回头换成mixbox里面的v2ray binary试试看

**Comment by mzz2017** [comment]
手输modprobe xt_TPROXY试试

**Comment by jsfaint** [comment]
用source code编译的v2ray提示
> 2019/12/08 12:37:46 不支持透明代理，设置透明代理失败内核未编译xt_TPROXY

换mixbox自带的v2ray提示
> 2019/12/08 12:38:38 不支持透明代理，设置透明代理失败v2ray-core版本低于4.19.1

tproxy driver已经挂载成功
```bash
$ lsmod | grep TPROXY
xt_TPROXY               1039  0
nf_tproxy_core          1347  1 xt_TPROXY,[permanent]
```

之后如果有其他进展我再来更新 :smile:

**Comment by mzz2017** [comment]
> 用source code编译的v2ray提示
> 
> > 2019/12/08 12:37:46 不支持透明代理，设置透明代理失败内核未编译xt_TPROXY
> 
> 换mixbox自带的v2ray提示
> 
> > 2019/12/08 12:38:38 不支持透明代理，设置透明代理失败v2ray-core版本低于4.19.1
> 
> tproxy driver已经挂载成功
> 
> ```shell
> $ lsmod | grep TPROXY
> xt_TPROXY               1039  0
> nf_tproxy_core          1347  1 xt_TPROXY,[permanent]
> ```
> 
> 之后如果有其他进展我再来更新

`modprobe -v xt_TPROXY` 可以成功吗，因为不同linux的指令支持的参数不一样，之前v2raya添加了-v参数。

**Comment by jsfaint** [comment]
看来modprobe被阉割掉了
```bash
$ modprobe -v xt_TPROXY
-ash: modprobe: not found
```

**Comment by mzz2017** [comment]
啊哈，这个问题我后来考虑到了，再新一版我会修掉的。
谢谢支持！

**Comment by mzz2017** [comment]
已发布v0.4.7
