### ISSUE TITLE
Linux server(cent os 7)

### ISSUE THREAD

**Issue by NoverNobida** [mzz2017/V2RayA#70]
请问是否支持Linux 服务器(cent os 7)？或者说需要什么额外的配置？我使用docker以及直接运行，配置好后都无法连接国外站点。因为国内服务器连接某些国外站点太慢，或者根本无法连接。

**Comment by mzz2017** [comment]
配置是怎么样的




mzz2017
m@mzz.pub




------------------ Original ------------------

**Comment by NoverNobida** [comment]
@mzz2017 国内服务器，centos7，amd64位，1核2G。我实际操作v2rayA是显示运行的，也没报错。但是无法连接国外站点。 （我是利用一个web应用“ [shiori](https://github.com/go-shiori/shiori) ”测试的，它可以为网页存档，所以正常情况无法存档国外访问不了的网站，我开启了v2rayA后，也无法连接存档）

**Comment by mzz2017** [comment]
光打开v2raya肯定不行，我是说你在gui上连接节点了吗，开了全局透明代理了吗




mzz2017
m@mzz.pub




------------------ Original ------------------

**Comment by NoverNobida** [comment]
@mzz2017 开了的。我添加了自己的vmess节点，打开了全局的透明代理，所有流量经过节点。
我是不是还需要打开什么端口之类的？

**Comment by mzz2017** [comment]
那倒不需要。之前只在ubuntu和debian的服务器上试过，centos7还真没试过。你是按照wiki的方法启的docker是吧

**Comment by mzz2017** [comment]
我过两天在centos上尝试复现一下

**Comment by NoverNobida** [comment]
@mzz2017  是的。我按照那个wiki弄的。我再试一试，感谢！

**Comment by mzz2017** [comment]
你可以尝试curl -v google.com有没有回应

**Comment by NoverNobida** [comment]
@mzz2017 我试了一下，可以的，然后 `wget` GitHub的release也很快。所以只是那个应用的问题。我用了v2rayA之后，不管打不打开代理，现在那个应用都不能工作了。T_T

**Comment by mzz2017** [comment]
为了避免一些问题，v2rayA的代理会绕过docker，如果你的那个应用跑在docker容器中是无法享受代理的，只会直连

**Comment by NoverNobida** [comment]
@mzz2017 原来如此，请问这个有解决方法吗？没有的话我只能把需要代理的docker应用换成主机部署的了。

**Comment by mzz2017** [comment]
https://docs.docker.com/config/daemon/systemd/#start-automatically-at-system-boot#httphttps-proxy
尝试为docker容器添加环境变量（较弱的一种代理），看问题是否可以得到解决。
docker在nat中有地址转换，我没有过多深入，如果你熟悉iptables方面的内容可以自行尝试解决，顺便也可以告诉我怎么解决的 :)

**Comment by NoverNobida** [comment]
感谢！我试试。

**Comment by mzz2017** [comment]
V2RayA的http(s)代理在20171端口，我不清楚这里的地址是否需要使用docker容器中宿主机网关地址，通过ip addr可以看到，比方说我这里docker0是172.17.0.1。

**Comment by NoverNobida** [comment]
我试了一下，貌似直接在 `docker run` 参数里面加上 `--network=host` 就可以了。这样它使用的网络就是宿主机网络，我实际测试了，发现可以连接国外网站。
