### ISSUE TITLE
V2RayA的docker部署暂未支持armhf构架的树莓派吗？

### ISSUE THREAD

**Issue by FxPixels** [mzz2017/v2rayA#72]
我在今年 2 月份的时候试了一次用 docker 部署， 发现是可以的，但是现在就不可以了，也不记得当初用了哪个版本。

现在docker logs报错 ：
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by mzz2017** [comment]
是的，因为所依赖的v2ray镜像没有arm架构镜像

**Comment by FxPixels** [comment]
> 是的，因为所依赖的v2ray镜像没有arm架构镜像

那…有准备做一个吗

**Comment by FxPixels** [comment]
![image](https://user-images.githubusercontent.com/25996313/80555075-bdac2f80-8a01-11ea-9929-b410a4809c0b.png)
这个就是2月25号之前部署的，不知道为啥能运行，后来就清除了树莓派上的docker所有容器和镜像，再拉下来就不行了。

**Comment by mzz2017** [comment]
ok 今天支持一下

**Comment by mzz2017** [comment]
https://hub.docker.com/r/mzz2017/v2raya/tags?page=1&name=0.7.0.1
