### ISSUE TITLE
提示：配置文件有问题或所需端口被占用

### ISSUE THREAD

**Issue by iamcheyan** [mzz2017/v2rayA#74]
### Version, approach of installation, operating system

1. What version of v2rayA are you using?
0.7.0.1

2. What approach of installation do you install V2rayA?
sudo apt-get install v2raya

3. What is your operating system and CPU architecture?
linux mint 19 & amd r5 3500u

### Description

安装完后，导入订阅，选择节点地址，连接不上，会显示：

`fail in connecting > v2rayA/core/v2ray: v2ray-core does not start normally, there may be a problem of the configuration file or the required port is occupied`

[](url)
![微信图片_20200503205447](https://user-images.githubusercontent.com/1495584/80914780-7ff03380-8d80-11ea-843a-452347c6d6c5.png)

**Comment by iamcheyan** [comment]
抱歉这不算bug，只是我使用问题反馈。

**Comment by mzz2017** [comment]
```bash
journalctl -u v2ray|tail -n 200
```

**Comment by iamcheyan** [comment]
> ```shell
> journalctl -u v2ray | 尾巴-n 200
> ```

20:54:00  systemd[1]: Stopping V2Ray - A unified platform for anti-censorship...
20:54:00  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
20:54:00  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
20:54:00  v2ray[6476]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
20:54:00  v2ray[6476]: A unified platform for anti-censorship.
20:54:00  v2ray[6476]: 2020/05/03 20:54:00 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
20:54:00  v2ray[6476]: v2ctl> Read config:  /etc/v2ray/config.json
20:54:23  systemd[1]: Stopping V2Ray - A unified platform for anti-censorship...
20:54:23  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
20:54:23  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
20:54:23  v2ray[6589]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
20:54:23  v2ray[6589]: A unified platform for anti-censorship.
20:54:23  v2ray[6589]: 2020/05/03 20:54:23 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
20:54:23  v2ray[6589]: v2ctl> Read config:  /etc/v2ray/config.json
21:08:39  systemd[1]: Stopping V2Ray - A unified platform for anti-censorship...
21:08:39  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:08:39  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:08:39  v2ray[10832]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:08:39  v2ray[10832]: A unified platform for anti-censorship.
21:08:39  v2ray[10832]: 2020/05/03 21:08:39 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:08:39  v2ray[10832]: v2ctl> Read config:  /etc/v2ray/config.json
21:09:34  systemd[1]: Stopping V2Ray - A unified platform for anti-censorship...
21:09:34  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:09:34  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:09:34  v2ray[11146]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:09:34  v2ray[11146]: A unified platform for anti-censorship.
21:09:34  v2ray[11146]: 2020/05/03 21:09:34 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:09:34  v2ray[11146]: v2ctl> Read config:  /etc/v2ray/config.json
21:09:35  v2ray[11146]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:09:35  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:09:35  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:09:35  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:09:35  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
21:09:35  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:09:35  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:09:35  v2ray[11174]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:09:35  v2ray[11174]: A unified platform for anti-censorship.
21:09:35  v2ray[11174]: 2020/05/03 21:09:35 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:09:35  v2ray[11174]: v2ctl> Read config:  /etc/v2ray/config.json
21:09:35  v2ray[11174]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:09:35  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:09:35  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:09:35  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:09:35  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
21:09:35  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:09:35  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:09:35  v2ray[11197]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:09:35  v2ray[11197]: A unified platform for anti-censorship.
21:09:36  v2ray[11197]: 2020/05/03 21:09:36 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:09:36  v2ray[11197]: v2ctl> Read config:  /etc/v2ray/config.json
21:09:36  v2ray[11197]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:09:36  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:09:36  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:09:36  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:09:36  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 3.
21:09:36  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:09:36  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:09:36  v2ray[11233]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:09:36  v2ray[11233]: A unified platform for anti-censorship.
21:09:36  v2ray[11233]: 2020/05/03 21:09:36 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:09:36  v2ray[11233]: v2ctl> Read config:  /etc/v2ray/config.json
21:09:36  v2ray[11233]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:09:36  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:09:36  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:09:37  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:09:37  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 4.
21:09:37  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:09:37  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:09:37  v2ray[11272]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:09:37  v2ray[11272]: A unified platform for anti-censorship.
21:09:37  v2ray[11272]: 2020/05/03 21:09:37 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:09:37  v2ray[11272]: v2ctl> Read config:  /etc/v2ray/config.json
21:09:37  v2ray[11272]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:09:37  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:09:37  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:09:37  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:09:37  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
21:09:37  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:09:37  systemd[1]: v2ray.service: Start request repeated too quickly.
21:09:37  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:09:37  systemd[1]: Failed to start V2Ray - A unified platform for anti-censorship.
21:17:02  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:17:02  v2ray[12160]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:17:02  v2ray[12160]: A unified platform for anti-censorship.
21:17:02  v2ray[12160]: 2020/05/03 21:17:02 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:17:02  v2ray[12160]: v2ctl> Read config:  /etc/v2ray/config.json
21:17:02  v2ray[12160]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:17:02  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:17:02  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:17:02  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:17:02  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
21:17:02  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:17:02  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:17:02  v2ray[12190]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:17:02  v2ray[12190]: A unified platform for anti-censorship.
21:17:03  v2ray[12190]: 2020/05/03 21:17:03 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:17:03  v2ray[12190]: v2ctl> Read config:  /etc/v2ray/config.json
21:17:03  v2ray[12190]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:17:03  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:17:03  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:17:03  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:17:03  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
21:17:03  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:17:03  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:17:03  v2ray[12211]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:17:03  v2ray[12211]: A unified platform for anti-censorship.
21:17:03  v2ray[12211]: 2020/05/03 21:17:03 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:17:03  v2ray[12211]: v2ctl> Read config:  /etc/v2ray/config.json
21:17:03  v2ray[12211]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:17:03  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:17:03  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:17:03  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:17:03  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 3.
21:17:03  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:17:03  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:17:03  v2ray[12233]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:17:03  v2ray[12233]: A unified platform for anti-censorship.
21:17:04  v2ray[12233]: 2020/05/03 21:17:04 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:17:04  v2ray[12233]: v2ctl> Read config:  /etc/v2ray/config.json
21:17:04  v2ray[12233]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:17:04  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:17:04  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:17:04  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:17:04  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 4.
21:17:04  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:17:04  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:17:04  v2ray[12254]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:17:04  v2ray[12254]: A unified platform for anti-censorship.
21:17:04  v2ray[12254]: 2020/05/03 21:17:04 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:17:04  v2ray[12254]: v2ctl> Read config:  /etc/v2ray/config.json
21:17:04  v2ray[12254]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:17:04  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:17:04  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:17:04  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:17:04  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
21:17:04  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:17:04  systemd[1]: v2ray.service: Start request repeated too quickly.
21:17:04  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:17:04  systemd[1]: Failed to start V2Ray - A unified platform for anti-censorship.
21:17:07  systemd[1]: v2ray.service: Start request repeated too quickly.
21:17:07  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:17:07  systemd[1]: Failed to start V2Ray - A unified platform for anti-censorship.
21:17:59  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:17:59  v2ray[13177]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:17:59  v2ray[13177]: A unified platform for anti-censorship.
21:17:59  v2ray[13177]: 2020/05/03 21:17:59 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:17:59  v2ray[13177]: v2ctl> Read config:  /etc/v2ray/config.json
21:17:59  v2ray[13177]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:17:59  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:17:59  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:18:00  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:18:00  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
21:18:00  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:18:00  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:18:00  v2ray[13202]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:18:00  v2ray[13202]: A unified platform for anti-censorship.
21:18:00  v2ray[13202]: 2020/05/03 21:18:00 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:18:00  v2ray[13202]: v2ctl> Read config:  /etc/v2ray/config.json
21:18:00  v2ray[13202]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:18:00  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:18:00  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:18:00  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:18:00  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
21:18:00  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:18:00  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:18:00  v2ray[13224]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:18:00  v2ray[13224]: A unified platform for anti-censorship.
21:18:00  v2ray[13224]: 2020/05/03 21:18:00 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:18:00  v2ray[13224]: v2ctl> Read config:  /etc/v2ray/config.json
21:18:00  v2ray[13224]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:18:00  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:18:00  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:18:01  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:18:01  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 3.
21:18:01  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:18:01  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:18:01  v2ray[13246]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:18:01  v2ray[13246]: A unified platform for anti-censorship.
21:18:01  v2ray[13246]: 2020/05/03 21:18:01 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:18:01  v2ray[13246]: v2ctl> Read config:  /etc/v2ray/config.json
21:18:01  v2ray[13246]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:18:01  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:18:01  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:18:01  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:18:01  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 4.
21:18:01  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:18:01  systemd[1]: Started V2Ray - A unified platform for anti-censorship.
21:18:01  v2ray[13268]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
21:18:01  v2ray[13268]: A unified platform for anti-censorship.
21:18:01  v2ray[13268]: 2020/05/03 21:18:01 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
21:18:01  v2ray[13268]: v2ctl> Read config:  /etc/v2ray/config.json
21:18:01  v2ray[13268]: Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12345 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:12345 > listen tcp 0.0.0.0:12345: bind: address already in use
21:18:01  systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
21:18:01  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:18:02  systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
21:18:02  systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
21:18:02  systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
21:18:02  systemd[1]: v2ray.service: Start request repeated too quickly.
21:18:02  systemd[1]: v2ray.service: Failed with result 'exit-code'.
21:18:02  systemd[1]: Failed to start V2Ray - A unified platform for anti-censorship.

**Comment by mzz2017** [comment]
12345端口被占用了，检查一下
 
netstat -tulpen|grep 12345

**Comment by iamcheyan** [comment]
> 12345端口被占用了，检查一下
> 
> netstat -tulpen | grep 12345

感谢，现在工作正常，非常好用！
