### ISSUE TITLE
manjaro下，v2rayA代理开启时，wifi状态为受限的连接

### ISSUE THREAD

**Issue by Leo4ML** [mzz2017/v2rayA#76]
#### 已使用v2rayA大半年

5月27日之前，v2rayA一直开机便自启，chrome的switchomega插件管理是否开启代理。一切正常。今天（5月27日）发现wifi状态为受限的连接，无法上网，公司内网外网皆无法联网。
```shell
systemctl stop v2raya
```
关掉v2raya服务后，上网正常。求问题解决~

**Comment by mzz2017** [comment]
最近进行过v2raya的版本更新，或对系统做过滚动更新吗

**Comment by mzz2017** [comment]
看起来是v2rayA的透明代理影响的？可以在设置里关掉看看，因为你用的switchomega在上网，除了shell翻墙不需要透明代理。

有几种可能的原因：
1. 滚动更新把iptables滚挂了
2. 节点挂了
3. 其他原因，需要更多信息

**Comment by mzz2017** [comment]
对于内网无法访问这一点，要看是域名无法解析，还是内网ip无法访问。
如果是前者是可以解释的，后者可能就不太好解释了。

**Comment by Leo4ML** [comment]
> 最近进行过v2raya的版本更新，或对系统做过滚动更新吗

1.之前用的一直是v2raya版本一直是0.7.0.1，未出现问题， 今天出现问题后，升级到0.7.0.3，问题依旧存在，应该能排除v2raya版本更新原因；
2.今天倒是对manjaro的pacman相关包更新过，但未涉及到系统更新，不确定是否和包更新相关；
3.节点一切正常，ipad，手机端，windows端皆正常（内网也都正常访问）；
4.内网无法访问是因为开启v2raya服务后，网络受限，内外网都无法访问；
目前我在尝试找到今天更新的pacman相关包的记录，看是否有涉及网络管理这块的内容了。如果还需要其他信息，还请告知，感谢开发者及时的回复！

**Comment by Leo4ML** [comment]
> 看起来是v2rayA的透明代理影响的？可以在设置里关掉看看，因为你用的switchomega在上网，除了shell翻墙不需要透明代理。
> 
> 有几种可能的原因：
> 
> 1. 滚动更新把iptables滚挂了
> 2. 节点挂了
> 3. 其他原因，需要更多信息

可以

> 看起来是v2rayA的透明代理影响的？可以在设置里关掉看看，因为你用的switchomega在上网，除了shell翻墙不需要透明代理。
> 
> 有几种可能的原因：
> 
> 1. 滚动更新把iptables滚挂了
> 2. 节点挂了
> 3. 其他原因，需要更多信息

## 问题解决！
是全局透明代理未关闭的原因，关掉后一切正常，启用后就会出现这个问题。奇怪的是，这个设置我从未修改过，之前一直无问题，怎么今天就出现问题了 Orz

再次感谢开发者对issue的关注和回复

**Comment by mzz2017** [comment]
那么我将暂时关闭这条issue，如果查明原因请直接reopen
