### ISSUE TITLE
fail in connecting > v2rayA/core/v2ray: v2ray-core does not start normally, there may be a problem of the configuration file or the required port is occupied

### ISSUE THREAD

**Issue by lycstar** [mzz2017/v2rayA#77]
archlinux，连接ssr节点报错

**Comment by mzz2017** [comment]
journalctl -u v2ray | tail -n 100

**Comment by exzhawk** [comment]
同样archlinux, 同样提示
journalctl -u v2ray 是以下重复
```
Jul 10 23:07:43 nas systemd[1]: Stopping V2Ray Service...
Jul 10 23:07:43 nas systemd[1]: v2ray.service: Succeeded.
Jul 10 23:07:43 nas systemd[1]: Stopped V2Ray Service.
Jul 10 23:07:54 nas systemd[1]: Started V2Ray Service.
Jul 10 23:07:54 nas v2ray[333707]: V2Ray 4.25.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
Jul 10 23:07:54 nas v2ray[333707]: A unified platform for anti-censorship.
Jul 10 23:07:54 nas v2ray[333707]: 2020/07/10 23:07:54 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Jul 10 23:07:54 nas v2ray[333707]: v2ctl> Read config:  /etc/v2ray/config.json
```

单独运行v2raya的log 是以下重复
```
2020/07/10 23:07:53 connect.go:39: Connect: begin
2020/07/10 23:08:09 connect.go:65: Connect: done
2020/07/10 23:08:09 [Warning] failed to connect > github.com/mzz2017/v2rayA/core/v2ray: v2ray-core does not start normally, there may be a problem of the configuration file or the required port is occupied
```

实际上v2ray服务已经正常启动了, 刷新网页就能看到正在运行

**Comment by lycstar** [comment]
> 同样archlinux, 同样提示
> 
> journalctl -u v2ray 是以下重复
> 
> ```
> 
> Jul 10 23:07:43 nas systemd[1]: Stopping V2Ray Service...
> 
> Jul 10 23:07:43 nas systemd[1]: v2ray.service: Succeeded.
> 
> Jul 10 23:07:43 nas systemd[1]: Stopped V2Ray Service.
> 
> Jul 10 23:07:54 nas systemd[1]: Started V2Ray Service.
> 
> Jul 10 23:07:54 nas v2ray[333707]: V2Ray 4.25.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
> 
> Jul 10 23:07:54 nas v2ray[333707]: A unified platform for anti-censorship.
> 
> Jul 10 23:07:54 nas v2ray[333707]: 2020/07/10 23:07:54 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
> 
> Jul 10 23:07:54 nas v2ray[333707]: v2ctl> Read config:  /etc/v2ray/config.json
> 
> ```
> 
> 
> 
> 单独运行v2raya的log 是以下重复
> 
> ```
> 
> 2020/07/10 23:07:53 connect.go:39: Connect: begin
> 
> 2020/07/10 23:08:09 connect.go:65: Connect: done
> 
> 2020/07/10 23:08:09 [Warning] failed to connect > github.com/mzz2017/v2rayA/core/v2ray: v2ray-core does not start normally, there may be a problem of the configuration file or the required port is occupied
> 
> ```
> 
> 
> 
> 实际上v2ray服务已经正常启动了, 刷新网页就能看到正在运行

我的不知道咋的后来自己就好了😅

**Comment by mzz2017** [comment]
> 同样archlinux, 同样提示
> journalctl -u v2ray 是以下重复
> 
> ```
> Jul 10 23:07:43 nas systemd[1]: Stopping V2Ray Service...
> Jul 10 23:07:43 nas systemd[1]: v2ray.service: Succeeded.
> Jul 10 23:07:43 nas systemd[1]: Stopped V2Ray Service.
> Jul 10 23:07:54 nas systemd[1]: Started V2Ray Service.
> Jul 10 23:07:54 nas v2ray[333707]: V2Ray 4.25.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
> Jul 10 23:07:54 nas v2ray[333707]: A unified platform for anti-censorship.
> Jul 10 23:07:54 nas v2ray[333707]: 2020/07/10 23:07:54 [Info] [v2ray.com/core/common/platform/ctlcmd:](http://v2ray.com/core/common/platform/ctlcmd:) <v2ctl message>
> Jul 10 23:07:54 nas v2ray[333707]: v2ctl> Read config:  /etc/v2ray/config.json
> ```
> 
> 单独运行v2raya的log 是以下重复
> 
> ```
> 2020/07/10 23:07:53 connect.go:39: Connect: begin
> 2020/07/10 23:08:09 connect.go:65: Connect: done
> 2020/07/10 23:08:09 [Warning] failed to connect > [github.com/mzz2017/v2rayA/core/v2ray:](http://github.com/mzz2017/v2rayA/core/v2ray:) v2ray-core does not start normally, there may be a problem of the configuration file or the required port is occupied
> ```
> 
> 实际上v2ray服务已经正常启动了, 刷新网页就能看到正在运行, 但在节点列表里不显示为已连接

这里是因为v2raya会读取/proc/net/tcp的端口信息来判断v2ray是否已正确启动，但这种方式可能会受不同的linux发行版影响无法获取到对应的端口监听情况，有时间的时候会将现在的方式从控制v2ray服务改成完全子进程形式启动v2ray来改善这一情况。

**Comment by zerobikappa** [comment]
I also encountered this error message. My archlinux machine with `v2raya` worked well until yesterday. Today after I upgraded my system, the `v2raya` stopped working and it showed this message "v2ray-core does not start normally, there may be a problem of the configuration file or the required port is occupied". And the `v2ray` showed this message "/usr/lib/systemd/system/v2ray.service:10: Special user nobody configured, this is not safe!". Tried to run `netstat` and found only `port 2017` was listening, `port 20170/20171/20172` was closed.

**Comment by mzz2017** [comment]
> I also encountered this error message. My archlinux machine with `v2raya` worked well until yesterday. Today after I upgraded my system, the `v2raya` stopped working and it showed this message "v2ray-core does not start normally, there may be a problem of the configuration file or the required port is occupied". And the `v2ray` showed this message "/usr/lib/systemd/system/v2ray.service:10: Special user nobody configured, this is not safe!". Tried to run `netstat` and found only `port 2017` was listening, `port 20170/20171/20172` was closed.

为了临时解决问题：
请将v2ray回退到4.27.0版本
v2ray-domain-list-community回退到20200822版本
v2ray-geoip回退到20200819版本

过段时间我将进行该问题的修复

**Comment by mzz2017** [comment]
v1.0.1已尝试对相关问题进行修复，我将把该ISSUE关闭。

如新版本仍不能解决该问题，请重新打开该ISSUE。

**Comment by zerobikappa** [comment]
@mzz2017 thank a lot. It works.

**Comment by ProMachine** [comment]
> v1.0.1已尝试对相关问题进行修复，我将把该ISSUE关闭。
> 
> 如新版本仍不能解决该问题，请重新打开该ISSUE。

建议放在教程显眼的位置⋯被坑太久了⋯
