### ISSUE TITLE
与我的另一个dns服务的容器有冲突

### ISSUE THREAD

**Issue by Super-pixle** [mzz2017/v2rayA#78]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
0.7.0.4
2. 你通过什么方式安装v2rayA
docker
3. 你所使用的操作系统、CPU架构
debian10 arm64

### 描述问题：

我的另一个容器有dns服务（网络是桥接，暴露53udp和tcp），v2raya是host网络。当两个服务同时运行时，v2raya的网络也会不正常，日志中全是下面这样的错误：
2020/06/03 16:09:02 ssr.go:95: [ssr] dial to 服务器网址:14238 error: dial tcp: lookup 服务器网址 on 127.0.0.53:53: read udp 127.0.0.1:23736->127.0.0.53:53: i/o timeout
此时在终端中运行dig，也不正常
![image](https://user-images.githubusercontent.com/44594408/83661571-e4f5ae00-a5f8-11ea-899f-3d865cd6f501.png)
把防止dns污染设置为关闭也不能解决问题

**Comment by mzz2017** [comment]
确定是冲突是吧，关闭任意一个都会解决？

尝试关闭透明代理，进v2raya容器装个nslookup看一下能不能查询dns。

**Comment by mzz2017** [comment]
给的信息找不到问题在哪里，因为在关闭防dns污染的情况下，即使开启透明代理使用的也是nat表，是不转发udp的。

udp不应该收到v2raya的影响。

**Comment by Super-pixle** [comment]
关闭全局透明代理后，冲突就没有了，我的dns服务也正常工作；输入上面的命令，没有任何返回值（不知道是否正常），手机（网关设置为宿主机的ip,dns也是宿主机ip）打开网站会提示name_not_resolved

**Comment by Super-pixle** [comment]
如果只关闭dns防污染，打开全局透明代理，也不跑任何dns服务，我的宿主机仍然提供dns服务，只不过是污染的；如果再关闭全局透明代理，就没有dns服务了，我的在其他设备nslookup就直接超时；是因为全局透明代理会转发53端口吗？希望可以完全关闭53端口的服务

**Comment by mzz2017** [comment]
hello，尝试编译dev分支，已加入端口白名单
```bash
sudo systemctl stop v2raya
sudo go build -o /usr/bin/v2raya .
sudo systemctl start v2raya
```
如没有golang环境我可使用下述编译好的二进制：
（This link will expire after 1 download or 1d 0h 0m）
https://send.firefox.com/download/4a0bd0f44d41f749/#S0CLf0lbCUJUcrVJV0QXZg

**Comment by mzz2017** [comment]
使用该版本，在透明代理的选项中填写出口白名单即可。

**Comment by Super-pixle** [comment]
请问这个怎么在docker下用啊？

**Comment by Super-pixle** [comment]
请问这个怎么在docker下用啊？

**Comment by mzz2017** [comment]
拉取源码，切换到dev分支后`docker-compose up --build`

**Comment by Super-pixle** [comment]
好的，我试试

**Comment by Super-pixle** [comment]
出错了
![image](https://user-images.githubusercontent.com/44594408/83715712-a5fb4300-a660-11ea-9743-c2edcfab7349.png)

**Comment by mzz2017** [comment]
你是使用git clone拉取的代码吗

**Comment by Super-pixle** [comment]
![image](https://user-images.githubusercontent.com/44594408/83715833-e6f35780-a660-11ea-9c15-918bdb377cda.png)

**Comment by mzz2017** [comment]
我这边运行正常，但你可以修改Dockerfile为
```dockerfile
FROM golang:alpine AS builder
ADD service /build/service
WORKDIR /build/service
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.io
RUN go build -o v2raya .

FROM v2fly/v2fly-core AS v2ray

FROM bgiddings/iptables:latest
COPY --from=builder /build/service/v2raya /usr/bin/
COPY --from=v2ray /usr/bin/v2ray/* /etc/v2ray/
ENV PATH=$PATH:/etc/v2ray
ENV GIN_MODE=release
EXPOSE 2017
ENTRYPOINT ["v2raya","--mode=universal"]
```

**Comment by Super-pixle** [comment]
改了dockerfile,又出错了
![image](https://user-images.githubusercontent.com/44594408/83718603-f1fdb600-a667-11ea-880a-09e376faa316.png)

**Comment by Super-pixle** [comment]
![image](https://user-images.githubusercontent.com/44594408/83720067-e8298200-a66a-11ea-8c6f-670e9bd84af5.png)
这个初始设置就已经包含了53端口了，还是和我的dns服务冲突

**Comment by mzz2017** [comment]
`iptables-save -t nat`应该已经有return对应端口了

你可以告诉我有冲突的docker镜像，以及你是如何run的，我这里进行复现一下

**Comment by Super-pixle** [comment]
docker run -p 53:53 -p 53:53/udp jasperhale/overture

**Comment by mzz2017** [comment]
你好，bug已修复，请尝试v0.7.0.5版本，谢谢

**Comment by Super-pixle** [comment]
嗯，解决了。非常感谢你。
