### ISSUE TITLE
[Feature]  应该补一下docker run命令的介绍

### ISSUE THREAD

**Issue by Justsoos** [mzz2017/V2RayA#8]
```
docker run -it -p 2017:2017 -p 20170:20170 -p 20171:20171 -p 20172:20172 mzz2017/v2raya
```
直接运行会出现提示 

> 不支持透明代理，设置透明代理失败获取v2ray-core版本失败

如题，用docker run命令运行应该补充到 docker hub 和 github readme 中。
另外，shell 是什么呢？
运行非透明/透明代理的参数设置也最好补充一下

**Comment by mzz2017** [comment]
已添加至README。

**Comment by mzz2017** [comment]
假定问题已解决
