### ISSUE TITLE
docker 版本0.7.0.1之后的版本，开启全局透明代理时，连接代理节点会报错

### ISSUE THREAD

**Issue by AnlakHui** [mzz2017/v2rayA#80]
报错如下：github.com/mzz2017/v2rayA/core/v2ray: github.com/mzz2017/v2rayA/core/v2ray: not support transparent proxy: > github.com/mzz2017/v2rayA/common/cmds: iptables-legacy -t nat -A V2RAY -m mark --mark 0xff -j RETURN iptables v1.8.3 (legacy): Couldn't load match `mark':No such file or directory Try `iptables -h' or 'iptables --help' for more information. > exit status 2

是不是docker版本不支持全局透明代理

**Comment by mzz2017** [comment]
docker版本需要`--net=host`及`--privileged`

**Comment by mzz2017** [comment]
另外最新版本是0.7.1并非0.7.0.1
