### ISSUE TITLE
安装后，访问web界面一片空白

### ISSUE THREAD

**Issue by Yofo-me** [mzz2017/v2rayA#83]
> 完成程序安装后，部署完v2rayA-web静态文件后，访问`http://127.0.0.1/v2rayA`一篇空白
```
系统: Ubuntu 20.04 LTS
web平台: Apache 2.4.41
v2rayA-web静态文件位置:    WEB根目录下/v2rayA
```
---
> 下面是程序输出日志：
![image.png](https://i.loli.net/2020/07/07/2A1ZuBJQXkjgPfr.png)

![image.png](https://i.loli.net/2020/07/07/ieknLJytvKEcDCm.png)

**Comment by mzz2017** [comment]
如果demo站工作正常，
请检查你的部署是否正确。
