### ISSUE TITLE
增加节点排序功能

### ISSUE THREAD

**Issue by ReddotCleaner** [mzz2017/v2rayA#84]
### 您想提出的功能特性是否和现有问题相关？

订阅节点只能按照配置文件内置顺序排序，在节点较多时无法快速定位低时延节点

### 功能特性内容

希望能增加节点排序功能，可根据协议、时延等进行节点排序。

**Comment by mzz2017** [comment]
时延方面的优化将在下个版本进行

**Comment by zz5678** [comment]
刚测了一下 v1.0.1 的 ping 后 排序，哈哈，目前 v2rayA，和我第一次用 shell 的 sort 排序用错一样：
![image](https://user-images.githubusercontent.com/67672527/94597479-33257000-02c0-11eb-8290-1845c25b4949.png)
