### ISSUE TITLE
[Feature] 能否添加对SOCKS5协议节点的支持

### ISSUE THREAD

**Issue by Smith1970** [mzz2017/v2rayA#89]
有些梯子提供在局域网内通过SOCKS5协议共享网络的功能，希望大佬能添加对SOCKS5协议节点的支持，以实现对梯子流量的全局透明代理

**Comment by mzz2017** [comment]
类似的高级功能实现可以通过[routingA](https://github.com/mzz2017/v2rayA/wiki/RoutingA)实现，下面是你提到的功能的routingA写法：
```python
# 下一行定义socks5出站协议，无用户密码的socks5协议则去除下面的user和pass
outbound: socksout = socks(address:"127.0.0.1", port:"18080", user: "my-username", pass: "my-password")
# 制定默认使用socksout的代理出站
default: socksout
# 下面两行定义大陆域名和IP直连，以及内网直连
domain(geosite:cn)->direct
ip(geoip:private, geoip:cn)->direct
```

**Comment by mzz2017** [comment]
RoutingA的设置在“规则端口的分流模式”的选项中

**Comment by Smith1970** [comment]
是只设置RoutingA不连接任何服务器节点即可实现么

**Comment by mzz2017** [comment]
需要连接节点，即使该节点是无效的。
记得透明代理选择“与规则端口所选模式一致”如果你使用透明代理的话。

**Comment by Smith1970** [comment]
添加了无效节点，成功了，感谢大佬

**Comment by lonble** [comment]
目前节点可以选择http/https，而实现socks出站还需要手写RoutingA以及添加无效节点。
我想问一下，是什么原因导致socks出站得绕这么一大圈，而不能像http/https出站一样直接当作节点添加？
