### ISSUE TITLE
[BUG] dns解析有问题会破坏ping测试，无法修改profile等

### ISSUE THREAD

**Issue by Justsoos** [mzz2017/V2RayA#9]
1，订阅里有一个或多个设置域名（解析无效）的节点，就无法继续执行ping了，会出现无法解析的提示并退出ping测试，估计在非订阅（多节点）下也是这样的情况。
最好能跳过不能解析的节点，并给出标记，其他节点继续ping
2，在首页subscription里点击修改订阅的名称等等，目前没有进一步动作（也许还在开发中？）
3，如果订阅内的节点可以手动修改内容--更高级的可以直接查看修改 config.json 就更好了 -- 用来查bug

**Comment by mzz2017** [comment]
1. 下个版本将修复
2. 本来是要出的，但是觉得没有特别大的意义，觉得可以把这个功能砍掉？
3. V2Ray的配置一般在/etc/v2ray/config.json
V2RayA的配置一般在/etc/v2ray/v2raya.json

**Comment by Justsoos** [comment]
2 的意义是，比如，有很多选择都用github分享，造成全部订阅的名字都一样，就尴尬了
3 目前没有vm进去看过怎么弄的，但它是指着可以修改 v2raya 的本地节点存储（数据库？），而不是 v2ray core 正在使用的那个 config.json

**Comment by mzz2017** [comment]
V2RayA会修改v2ray-core的config.json，并且控制服务的重启来更新配置，而v2raya.json用来保存节点和设置等信息，相当于数据库。

已了解，会在将来增加这一feature

**Comment by mzz2017** [comment]
已更新

**Comment by Justsoos** [comment]
问个docker的题外话，几天前第一次从 hub 下 latest 
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mzz2017/v2raya      latest              5d4e61bc1707        5 days ago          903MB
```
但今天找，这个RepoDigests是ec70726b671ab6caeb853d7ad8439290e94770feaee0c720d1bf57a48ae57a05 的在 hub 上没有存在？是手动删除的吗？

```json
[
    {
        "Id": "sha256:5d4e61bc170775dfa7054dadac3b18a94dbbfecd55cd5a167b67e088a5784b69",
        "RepoTags": [
            "mzz2017/v2raya:latest"
        ],
        "RepoDigests": [
            "mzz2017/v2raya@sha256:ec70726b671ab6caeb853d7ad8439290e94770feaee0c720d1bf57a48ae57a05"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-12-09T14:25:02.437346196Z",
```

**Comment by mzz2017** [comment]
docker镜像是用travis自动构建的，应该是latest镜像更新后sha1就不同了。

**Comment by Justsoos** [comment]
> docker镜像是用travis自动构建的，应该是latest镜像更新后hash就不同了。

看来还真是这样，这也意味着，docker hub 的 tag latest 可以是个恶意软件的版本藏毒窝棚了。
