### ISSUE TITLE
新版v2ray改了/etc/v2ray到/usr/local/etc/v2ray了

### ISSUE THREAD

**Issue by PangciPG** [mzz2017/v2rayA#93]
新版v2ray改了/etc/v2ray到/usr/local/etc/v2ray了

**Comment by mzz2017** [comment]
有任何影响吗

**Comment by withstraw** [comment]
我的电脑下根本没有/usr/local/etc/v2ray，/usr/local/bin/v2ray目录，结果就是v2ray启动失败，然后我改了v2ray的exec_start,v2raya启动又会报错
nutsdb.go:23: db.buildIndexes error: when build hintIndex readAt err: offset out of mapped region

**Comment by withstraw** [comment]
![image](https://user-images.githubusercontent.com/62787567/92126536-e1a9d280-ee32-11ea-9e10-6accba677176.png)

**Comment by withstraw** [comment]
![image](https://user-images.githubusercontent.com/62787567/92126945-6268ce80-ee33-11ea-8c61-85ee0a584edc.png)

**Comment by mzz2017** [comment]
v1.0.1已尝试对相关问题进行修复，我将把该ISSUE关闭。

如新版本仍不能解决该问题，请重新打开该ISSUE。
