### ISSUE TITLE
v2rayA  failed connect to server in Ubuntu 20.04.1

### ISSUE THREAD

**Issue by qahehe** [mzz2017/v2rayA#95]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA

debian_amd64_v1.0.1.deb
2. 你通过什么方式安装v2rayA
 dpkg -i 
3. 你所使用的操作系统
ubuntu 20.04.1 LTS

### 描述问题：

![Screenshot from 2020-09-07 10-24-25](https://user-images.githubusercontent.com/25258443/92342892-d84f8d00-f0f4-11ea-9ff1-bc756176211f.png)

主要是它经常failed to connect > github.com/mzz2017/v2rayA/core/v2ray: WriteV2rayConfig > open /etc/v2ray/config.json: no such file or directory

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志



```

**Comment by mzz2017** [comment]
1. 你是通过什么安装的v2ray
2. 贴一下 systemctl status v2ray

**Comment by qahehe** [comment]
> 1. 你是通过什么安装的v2ray
> 2. 贴一下 systemctl status v2ray

1.通过下载installer_debian_amd64_v1.0.1.deb，然后通过sudo dpkg -i installer_debian_amd64_v1.0.1.deb安装。我把deb文件名改为v2ray.deb才成功安装的。
2.
![Screenshot from 2020-09-07 10-42-27](https://user-images.githubusercontent.com/25258443/92343653-e0a8c780-f0f6-11ea-892d-1d54290de72d.png)

**Comment by mzz2017** [comment]
你好 v2rayA基于v2ray，你需要首先安装v2ray

见https://github.com/mzz2017/v2rayA/wiki/Usage

**Comment by qahehe** [comment]
> 你好 v2rayA基于v2ray，你需要首先安装v2ray
> 
> 见https://github.com/mzz2017/v2rayA/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

好的，已经连上了，谢谢大佬帮忙
