### ISSUE TITLE
我尝试了好几种代理，代理不成功，疑惑.jpg

### ISSUE THREAD

**Issue by zygds** [mzz2017/v2rayA#97]
### 版本、安装方式、系统
![image](https://user-images.githubusercontent.com/50038957/93659221-979d2f80-fa75-11ea-88a7-4e0484fa15a6.png)
![image](https://user-images.githubusercontent.com/50038957/93659235-b6032b00-fa75-11ea-8b2b-fc0ab36da587.png)
![image](https://user-images.githubusercontent.com/50038957/93659242-c3b8b080-fa75-11ea-829a-94e5dbb2be47.png)
![image](https://user-images.githubusercontent.com/50038957/93659250-d03d0900-fa75-11ea-85cd-57bdcca9ee2a.png)
![image](https://user-images.githubusercontent.com/50038957/93659261-e8ad2380-fa75-11ea-9c89-6db9d3fd938c.png)

1. 你在使用什么版本的v2rayA
1.0.1
2. 你通过什么方式安装v2rayA
wiki ubuntu 
3. 你所使用的操作系统
ubuntu 

### v2rayA运行日志（Optional）：

 ```bash
 # daemon mode
 journalctl -u v2ray | tail -n 50
 journalctl -u v2raya | tail -n 50
 
 # docker mode
 docker logs v2raya_backend
 ```
```shell
# 此处贴入运行日志



```

**Comment by mzz2017** [comment]
把自定义路由规则改成大陆白名单

**Comment by zygds** [comment]
![image](https://user-images.githubusercontent.com/50038957/93661164-392d7c80-fa88-11ea-8b4c-4e7fa055c0e2.png)
我改了，依然连接不上

**Comment by zygds** [comment]
![image](https://user-images.githubusercontent.com/50038957/93661208-95909c00-fa88-11ea-9bb2-96785a149cbe.png)
这个协议是是不支持马？

**Comment by mzz2017** [comment]
勾选你的节点，点左上角http测试，看通不通
不通报告一下协议

**Comment by zygds** [comment]
我换了，抱歉，之前删了，现在用的V2RAYL
