### ISSUE TITLE
使用Proxy Only GFWList模式，在开启openvpn后，无法访问内网gitlab页面

### ISSUE THREAD

**Issue by YahuiAn** [mzz2017/v2rayA#98]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
v1.0.1

2. 你通过什么方式安装v2rayA
docker-compose

3. 你所使用的操作系统
ubuntu 20.04

### 描述问题：

使用Proxy Only GFWList模式，在开启openvpn后，无法访问内网gitlab页面，关闭系统代理后，可以正常访问gitlab。

![image](https://user-images.githubusercontent.com/39142491/93784322-75670580-fc5f-11ea-93e6-a19d5d2d2a2e.png)

![image](https://user-images.githubusercontent.com/39142491/93784416-94fe2e00-fc5f-11ea-8d4a-7978893e4441.png)

![image](https://user-images.githubusercontent.com/39142491/93784738-e9091280-fc5f-11ea-8b7a-33aa4f8bf11d.png)

### v2rayA运行日志（Optional）：

 ```bash
 # docker mode
 ```
```shell
# 此处贴入运行日志
Quitting...
V2RayLocationAsset is /usr/share/v2ray
V2Ray binary is at /usr/share/v2ray/v2ray
v2rayA working directory is /
Version: 1.0.1
v2rayA is listening at http://127.0.0.1:2017
v2rayA is listening at http://192.168.1.6:2017
v2rayA is listening at http://172.17.0.1:2017
v2rayA is listening at http://[::1:2017]



```

**Comment by mzz2017** [comment]
可能是系统代理的问题，可以尝试关掉系统代理打开透明代理。

透明代理可以正常工作吗？

**Comment by YahuiAn** [comment]
关掉系统代理并打开透明代理后，可以正常访问啦。非常感谢～
我现在设置的是，GFW List 全局透明代理，想问问有什么优缺点吗？

**Comment by mzz2017** [comment]
缺点是什么都能代理，连docker都代理了

dns防污染选个防劫持然后开增强模式可以规避上述问题。

**Comment by YahuiAn** [comment]
好的，多谢啦👍👍👍
